### ISSUE TITLE
Use consistent view.seqno terminology

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1187]
We're aiming to use consistent terminology in our external API, where transactions execute in a _view_ at a _seqno_. We use this in a few places, but many places still use the old _term_ and _commit_.

- [x] Rename response headers (`x-ccf-term` to `x-ccf-view`)
- [x] Remove `x-ccf-global-commit` header (potentially a separate issue, but for clarity it would be nice to announce at the same time)
- [x] Update documentation to use new terminology. In particular, to talk about `Transaction IDs` composed of `view.seqno`
- [x] Update all external/sample code to use new terminology

**Comment by achamayou** [comment]
@eddyashton I think we want `x-ccf-tx-view` and `x-ccf-tx-seqno`, with the documentation describing those two values as Transaction ID. The status of that transaction can then be queried through the tx endpoint.

**Comment by achamayou** [comment]
- [ ] Update naming in Python infra for clarity, since it is visible through the start_test_network and recovery scripts

**Comment by achamayou** [comment]
So I think #1127 wraps this up effectively. It does not remove global_commit for now, because we'd need to update the perf tests substantially, but it's removed from the documentation.

I think there's follow up work on improving the documentation around the user RPC/transaction flow, but I'll do that separately.
