### ISSUE TITLE
Third party Javascript libraries.

### ISSUE THREAD

**Issue by jazzybluesea** [microsoft/CCF#1205]
Currently the quickjs engine allows including javascript libraries as byte code, and these libraries would be available to javascript handlers.  The ask here is to add support for including a set of javascript libraries and create a sample showing how to do it.

I believe there is already a related issue, if so please feel free to close this.

Thank you.

**Comment by achamayou** [comment]
I think the ideal mechanism for this would be to have support for QuickJS's module functionality, but have it implemented in terms of a table lookup in the CCF KV.

**Comment by letmaik** [comment]
@achamayou and I had a chat and we came up with the following.

At the lowest level we will add support for [native JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) where each module is stored separately under a given name in a kv map. It is up to the user to decide on module names, they are opaque and don't have a semantic meaning (e.g. relative paths). The runtime environment is closer to browsers than node.js (we will *not* emulate `require` etc.).

The existing library packaging ecosystem is complex and does not directly fit into the native JavaScript module support described above. The most popular packaging manager (npm) is meant for use in node.js and relies on extra tooling for use in browsers (e.g. webpack). In order to abstract from any node.js mechanisms (`package.json`, `require()`, ...) we recommend users to create bundles where a bundle is a single file/module containing all (transitive) dependencies and which exports a selected set of functions/objects. Bundles can be created with existing tools like webpack. Using bundles also avoids version conflicts in case different top-level modules require different dependency versions (they can share bundles, but they don't have to).

Though not strictly related to the topic of third-party libraries, I will discuss app endpoints here, too, as it relates to modules. The idea is that each app endpoint is a JavaScript module that must [export a default](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) function à la `export default function (a,b,c) { ... } `. This function is called from C++. Endpoint modules are otherwise not special and can import other modules (e.g. library bundles) as described above. Endpoints (independent of the language they are implemented in) are described declaratively, e.g. with JSON (tbd).

For all of the above, we will provide end-to-end samples.

cc @eddyashton

**Comment by eddyashton** [comment]
Looks reasonable, thanks for writing this up.

We should clarify whether these modules are readable/useable from governance scripts or just from JS app scripts. Assuming these are all governance-specified it should be fine to use them in governance as well.

What's the benefit of being unopinionated on module names? If we're going to look like a website rather than a Node app, can't we say all imports look something like `import ... from '/app/modules/foo.js'`. That would be at key `"foo"` in some `ccf.js_modules` table, but would let us write a `GET /app/modules/{module_name}` endpoint to inspect the modules?

**Comment by letmaik** [comment]
> We should clarify whether these modules are readable/useable from governance scripts or just from JS app scripts. Assuming these are all governance-specified it should be fine to use them in governance as well.

Probably? Maybe something @achamayou can clarify.

> What's the benefit of being unopinionated on module names? If we're going to look like a website rather than a Node app, can't we say all imports look something like `import ... from '/app/modules/foo.js'`. That would be at key `"foo"` in some `ccf.js_modules` table, but would let us write a `GET /app/modules/{module_name}` endpoint to inspect the modules?

Sure, a naming convention is fine as well, I only wanted to emphasize there should be no nesting context, e.g. with relative paths in subsequent imports. It's a bit more effort to parse the module name out of the full path to look it up in the kv, but that's fine. I would probably include `.js` in the module name though, for future compatibility with WASM modules. So `GET /app/modules/{module_name}.js` and `"{module_name}.js` in `ccf.modules`. If the scripts are for gov and apps, then probably `/app` is not the right prefix.

**Comment by achamayou** [comment]
For now, both the JS endpoints and their dependencies are installed through governance proposals, and are de-facto public as a result (regardless of how we end up storing them). There doesn't seem to be a reason to make modules inaccessible from the constitution, because their individual use would amount to a constitution change, through the same rules.

There is the same problem as with every other script when using dependencies: delegation. Special voting restrictions that would apply just to the constitution potentially do not apply to modules being imported. Members have to watch out for that.

It would become interesting to split the dependencies table if we wanted to support confidential application code and therefore confidential dependencies. That requires creating a new governance flow, and should be looked at as a separate change in my opinion.

**Comment by achamayou** [comment]
We have a generic mechanism to read public tables (gov/read). I think we should stick to that, and extend it if necessary rather than build something specific to modules.

**Comment by letmaik** [comment]
PR #1469 implements the foundation for this. What's missing after that is an end-to-end sample of bundling some existing dependencies into a module and using it from an endpoint.

**Comment by letmaik** [comment]
PR https://github.com/microsoft/CCF/pull/1484 is the next piece in the puzzle.
Any further work will be on polishing this (e.g. better tooling support, like https://github.com/microsoft/CCF/issues/1479) and finalizing how endpoints work exactly.
