### ISSUE TITLE
Support for historical queries

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1207]
It should be possible for users to query the service to get the value of a specific key at a given version.

_More details to follow..._

**Comment by eddyashton** [comment]
Summarising some early design discussions on this:

- A node can store old ledger entries and materialised instances of the KV in-memory, which do not interact with the 'current' KV used for consensus.
- To verify the integrity of a KV reconstructed from ledger entries read from the host, we need to replay from the last signature _before_ this version to the first signature _after_ it. We must check the validity of the latter signature, since the entries now come from an untrusted host (normally, they'd come over an integrity-protected channel directly from a trusted node).
- Our current method of fetching ledger entries uses the ringbuffer and is asynchronous. We cannot do this within an RPC. Either we need to add an ECALL to read these, or we need to pre-fetch targeted historical entries. The latter seems preferable, making these requests 2-stage and adding a clear "Not fetched yet" state while entries are slowly fetched/replayed.
- The simplest approach is to make this an entirely node-local system. Eventually we may look at coordination across nodes, with each responsible for some range of historical versions, to quickly service historical read requests.
- We should establish whether the common use case is querying a _single_ version or a _range_ of versions, and make sure we efficiently maintain the latter if needed.

**Comment by jumaffre** [comment]
With regards to "we need to replay from the last signature before this version", this will involve either fetching the signature closing the previous chunk or keeping a flag indicating whether each transaction in the ledger is a signature.

**Comment by achamayou** [comment]
I think we're going to want the flag for many reasons. We could also decide to duplicate transactions across chunks, and always have the last Tx in a chunk be copied at the beginning of the next. It'd make chunks verifiable/auditable on their own, it's slightly wasteful but practical in other ways. To be discussed.

**Comment by eddyashton** [comment]
Historical queries are supported since #1267.

Future improvements are tracked in other issues:
 - #1237 will allow us to request the desired signature directly, rather than searching linearly for it.
 - #1269 will reduce memory consumption by only cloning required tables.
 - [Snapshotting](https://github.com/microsoft/CCF/milestone/12) may allow us to serve a more complete historical state, of all writes _visible at_ rather than merely _produced by_ the target version.
