### ISSUE TITLE
Record both domain and IP in node certificate SAN

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1257]
We currently only support either the node's RPC IP address or domain (if `--domain` is passed to `cchost`) in the Subject Alternative Name of the node's x509 certificate. 

It might be useful to support both IP and DNS in there so that an operator can connect to a node _securely_ without relying on the DNS/load balancer to to be up and running.

**Comment by achamayou** [comment]
@jumaffre https://tools.ietf.org/html/rfc5280#section-4.2.1.6 having iPAddress in subjectAltName is definitely legal. As previously discussed, this would be useful in testing, or perhaps in operations.

**Comment by grcignav** [comment]
What if both Subject and the list of SANs were fully configurable at node startup time as arguments? In K8s for example, the node may not be able to find out its publicly-routable IP.

**Comment by achamayou** [comment]
@grcignav the public rpc address is already an optional flag, although it defaults to the local rpc address if not set and there is no way to modify it later.

It’s not impossible to make it mutable, but the cert would need to be regenerated, so it’s not quite trivial either.

Ideally most access is through the DNS, and the IP is there as an emergency facility in case there’s something wrong with the SLB for example. So having just the local IP could be enough since the admin would presumably be able to access the machine directly.

**Comment by jumaffre** [comment]
As discussed, it would be preferable to offer more flexibility on this and let operators pass as many fields they want to include in the node's certificate SAN field, e.g. `cchost --san <some_public_ip> --san domain1 --san domain2 ...`. 

The subject field is currently set to `CN = CCF Node` should probably be configurable as well.

On a side note, we should sort out the expiry of our certificates too as they are currently hard coded as : 
```
Validity
            Not Before: Nov  1 00:00:00 2019 GMT
            Not After : Dec 31 23:59:59 2021 GMT
```

**Comment by achamayou** [comment]
We may want an additional format/qualifier to let users specify if that's a DNS Name or an IP Address.

**Comment by jumaffre** [comment]
@achamayou I thought we could auto-detect that with the [`ip_to_binary`](https://github.com/microsoft/CCF/blob/master/src/ds/net.h#L22) function that we already have.

**Comment by achamayou** [comment]
@jumaffre we can, but it's not clear cut that we should, because at least some older software effectively requires that ip addresses are set in DNS entries, see https://security.stackexchange.com/questions/160787/ip-address-in-subjectaltname

Giving the user freedom to set this explicitly seems prudent.

**Comment by achamayou** [comment]
So how about:

```
cchost --cn "Some Name" --san "iPAddress:10.0.04" --san "subjectAltName:foo.domain.tld"
```
