### ISSUE TITLE
On primary, KV local hooks are not triggered in total transaction order

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1368]
On the primary node, KV hooks are not currently triggered in the same order as the total order of the transactions they correspond to. For example, for 2 concurrent RPCs executed by the primary and which trigger a local hook, it is possible that the hook of the first transaction (executed a version `V`) is triggered _after_ the hook of the second transaction (executed at version `V+1`). 

Note that this issue does not happen on the backups as all write sets are applied sequentially and by the same thread, thanks to the Raft lock in `recv_append_entries()`. This is not an issue for global hooks either which are directly triggered by the consensus thread (on consensus commit). 

In particular, this is an issue for Raft reconfiguration in which new nodes are added to a new configuration whenever (local hook) a new node is `TRUSTED` by the KV. The `add_configuration` function below, which specifies that it should be called when the Raft lock is taken, is actually called _without_ acquiring lock on the primary. Concurrent rollback/compact on the consensus thread would cause concurrent access to the `configurations` and `nodes` members.
https://github.com/microsoft/CCF/blob/ffdb7d56df8425c861d5ad278e59969983ba3917/src/consensus/raft/raft.h#L287-L292

**Comment by eddyashton** [comment]
After looking at the code for a while, I'm not sure this description is completely correct. As far as I can tell, the hooks will always be triggered in order since they are called while the map is locked. All changes to a map (whether from `Tx::commit` or a rollback) happen under this lock, in `apply_views`, and the hooks are triggered at the same time under the same lock, in the same order. This does _not_ apply to hooks on different maps, so it is completely possible for a system to see hook calls for `V+1` followed by `V` on different maps.

However this level of complication is still undesirable, so here are our plans for replacing existing hooks:

- Raft Configuration. This is the hook on the nodes table described above. The problem is the disconnect between when the consensus is told of configuration changes (in a hook, during tx commit), and when it actually needs that configuration (when it is replicating the tx's changes). We will remove this gap, and pass the configuration directly to `Raft::replicate`. Under the existing lock in `replicate`, we will examine the configuration metadata associated with each batch, and call `add_configuration` as appropriate at this point. The precise format of this metadata and how it is constructed are still under discussion.
- Encryption Keys. There is a hook on the secrets table which updates the encryption keys (`encryptor->update_encryption_key`). This won't work in a multithreaded context. It is currently possible for transaction `V+1` to be serialised (and encrypted) _before_ transaction `V`, if they have no conflicting dependencies, in which case `V+1` will use the wrong encryptor. There is an implicit dependency on the last-written secrets for _every_ transaction, and this is currently hidden by the hook update. We can either make this explicit (read the secrets to construct an encryptor in every transaction, and re-execute on any resulting conflicts around rekeying), or track this dependency similarly to what we do with the execution Term (take a digest of the secrets used for the encryptor, pass this with the batch in `store->commit` and re-encrypt on mismatches). A variant on the latter approach would be to do encryption later, separately from serialisation, once we have the total order and are about to replicate - at this point we know the secrets for each version we have, so can reliably encrypt them with the correct encryptor.

**Comment by achamayou** [comment]
@eddyashton there are weaker guarantees due to map locking, but not execution of the hooks in total order, so the title and the description are still correct I think. The impact on raft is a bit subtle, because although the hook calls on the node table are effectively serialised by the map lock, and it isn't possible to lock them correctly on the raft side without causing a dead-lock.

For these reasons, the current mechanism isn't functionally sound and needs to be replaced, likely with the approach you have have described.

**Comment by achamayou** [comment]
I've been looking at implementing a solution to this issue, and I think it could be done this way:

1. Add a new `set_map_hook(map_name, hook)` to `Store`
2. `hook` is still executed on `post_commit()`. In some cases (*), such as ledger secrets update, this is the right time to apply side effects. But in many other cases, `hook` produces another callable `side_effect`, which is either:
  - Bundled with the serialised transaction and heads to `replicate()`
  - Returned to consensus when serialised transactions are applied
3. `side_effect` can be tagged either `on_order` or `on_global_commit`. If it's the former, consensus will execute `side_effect` immediately during `replicate()`, or before deserialising the next transaction on a follower. If it's the latter, the consensus will push `side_effect` to a queue, from which it will be popped for execution once global commit has moved past it.

(*) To clarify, this execution "time" is probably what we want for hooks that have side effects on the Store itself (ie. elements of the store other than tables themselves, such as secrets). Later "times" are for hooks that have side effects on consensus instead. We may or may not want to reflect this in the types.
