### ISSUE TITLE
Schema API is failing with URL query parsing error

### ISSUE THREAD

**Issue by syhamza** [microsoft/CCF#1375]
RPC call to api/schema is failing with URL query parsing error. Tried this based on the instructions[ here](https://microsoft.github.io/CCF/v0.11.1/users/rpc_api.html?highlight=api%20schema)

Just follow the instructions from the docs. Following error is returned:

> Unable to parse URL query value: method=tx ([json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'tx')

Schema of the request API is returned.

Running on virtual enclave setup on CCF release 0.11.1

**Comment by eddyashton** [comment]
The suggested curl line is wrong - the quotes around `"tx"` will be swallowed by the terminal, but are actually required by the parsing code on the CCF node. The fix is to escape the quotes, or wrap the entire URL in `'`s. Any of the following should work:
`curl https://.../schema?method=\"tx\" ...`
`curl https://.../schema?method=%22tx%22 ...`
`curl 'https://.../schema?method="tx"' ...`

I've opened #1377 to fix the docs, and we have a plan to remove the requirement for quotemarks in future.

**Comment by syhamza** [comment]
Got it. Thanks Eddy!
