### ISSUE TITLE
Package Python infra/utilities

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1382]
We should export some of our Python infra for easy consumption of some of our tooling. More specifically:
- **Users** should be able to connect to a CCF service and issue requests (HTTP or websocket) and verify transaction receipts.
- **Members/Operators** should be able to do what **users** can do _as well as_ issue and vote for proposals and parse/verify the ledger.

As such, the following files should be cleaned up and packaged to be release on PyPi: 
- `clients.py` - we should only ship the `request` and `websocket` clients and clean up a few things (e.g. the `result` response field). 
- `ledger.py` - which should support verifying multiple chunks (see https://github.com/microsoft/CCF/issues/1275). 
- `checker.py` to let clients verify that their transactions has been committed. 
- `proposal_generator.py` to let members/operators generate proposals conveniently.

The `ccf` python package should be published on PyPi with, for now at least, the same release cycle as the main C++ framework. 

---

Tasks: 
- [x] Package relevant Python classes. See #1380 
- [x] Cleanup package
- [x] Document package and automatically include in Sphinx
- [x] Automated releases to PyPi

**Comment by achamayou** [comment]
@lynshi your feedback would be very welcome.

**Comment by lynshi** [comment]
These enhancements are great! I think it addresses our issues quite well:
1. `clients.py` reduces code duplication for common procedures, such as signing requests and providing identities.
2. `ledger.py` supporting multiple chunks will make it easier to load files and parse entire ledgers for offline verification.
3. `checker.py` improves the end-to-end story for the user since they won't have to figure out how to verify commits for themselves.
4. `proposal_generator.py` makes it easier for members/operators to submit proposals without learning Lua or reading through the existing test infra. It will also give users a stable API (such as when the scripting language changes).

I'm happy to review associated PRs as well.
