### ISSUE TITLE
Make JS KV API look like standard JS types

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1530]
We should reduce friction for new developers by basing our API on existing types. This should remove learning humps and also make it easier to build a stub KV for sandboxed testing.

The key question is how we should expose a `TxView`. It looks like the closest approach is to build something that looks quite like a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), although we cannot offer the same or stable iteration order.

We can at least rename our methods to `set`, `get`, and `delete`. We can also easily add a `has` method.

Beyond this, we should be able to support `forEach`, and `size` (not currently tracked in C++, but could be). We may also be able to provide `@@iterator` support.

**Comment by letmaik** [comment]
In addition to renaming, this should also extend the supported key and value types so that it matches what `Map` does (same type in and out). Currently, only string is allowed for both key and value.

**Comment by letmaik** [comment]
Some background on JavaScript's `Map`:
- Allows to store arbitrary types as keys and values. Retrieving them returns the same, in case of objects the same reference.
- No de-/serialization is applied.
- [Key equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Key_equality) is roughly `===`, which for objects means that they are equal if they have the same reference.

Since CCF's KV relies on serialization it is impossible to achieve exactly the same semantics as `Map` (in addition to the already mentioned insertion order discrepancy). There are a few options with different trade-offs:

## Partially implement `Map` and document differences

Here, the KV is modelled after the `Map` interface and behaves *roughly* the same, and for 95% of cases identically.

This solution relies on storing type information (tags) together with keys/values such that on deserialization the correct type is returned. To avoid an explosion of type tags and possibly getting it wrong, only the following tags would exist:
- string: common type that should be efficient without relying on extra parsing
- ArrayBuffer: needed for binary data or custom encodings
- JSON: fall-back for all other serializable JSON-serializable types

Differences to `Map`:
- Floats (whether stand-alone or inside objects) may lose some precision during JSON encoding.
- `NaN`/`Infinity`/`undefined` (whether stand-alone or inside objects) are unsupported since JSON does not support them.
- ArrayBuffers inside objects are unsupported since JSON does not support them.
- Any other non-JSON-serializable types (whether stand-alone or inside objects) are unsupported, e.g. `Date`.
- Using objects as keys would not have reference key equality semantics but would rely on the JSON serialization and therefore should be strongly discouraged (as it would be easy to arrive at difference serializations, e.g. with different field orderings etc.).
- If `.keys()`/`.values()` etc. are exposed then elements would not be returned in insertion order.

Note that any time I mentioned "unsupported" in JSON context it means there will be no error but instead the value will be converted to a string (and then subsequently returned back as string), e.g. for `Date`, or converted to another placeholder value, e.g. `NaN` becomes `null`, `ArrayBuffer` becomes `{}`.

Usage example:
```js
ccf.kv.msgs.set(1, {text: "foo"});
let msg = ccf.kv.msgs.get(1);
console.log(msg.text);
```

## Implement [`Storage`](https://developer.mozilla.org/en-US/docs/Web/API/Storage)

The Web Storage API defines the Storage interface, which is used for `localStorage` for example.
Keys and values must be strings. A list of all keys can be retrieved iteratively via `.key(i)` without guarantees on order.
Storing binary data is inefficient as it has to be base64 (or similar) encoded and decoded.

This is roughly what CCF offers now, except for different method names and missing `.clear()` and `.key()` methods.
There are no differences in semantics between CCF and the Storage API. 

Usage example:
```js
ccf.kv.msgs.setItem("1", JSON.stringify({text: "foo"}));
let msg = JSON.parse(ccf.kv.msgs.getItem("1"));
console.log(msg.text);
```

## Custom interface - `Map`-like plus explicit types

Similar to `Map`, arbitrary types can be stored, but instead of using tagged values, the app itself must provide the types.
Since it is a custom interface there are no claims of being compatible with existing interfaces.
Supported types could be: int32, int64, float32, float64, bool, string, json, arraybuffer.
By explicitly making the developer state that an object is encoded as JSON it is obvious that all the limitations of JSON would apply.

A downside of this approach is that since there are no type tags, the developer has to be careful when using multiple key types (not that this is recommended), because then key conflicts may arise if the encoded representation of two types is identical for a given key. It's a corner case but worth mentioning, since the illusion is given that CCF deals with it somehow (at least in Usage example 2).

Usage example 1:
```js
let msgs = ccf.kv.msgs.typed(ccf.int32, ccf.json);
msgs.set(1, {text: "foo"});
let msg = msgs.get(1);
console.log(msg.text);
```

Usage example 2 (alternative):
```js
ccf.kv.msgs.set(ccf.int32, ccf.json, 1, {text: "foo"});
let msg = ccf.kv.msgs.get(ccf.int32, ccf.json, 1);
console.log(msg.text);
```

## Custom interface - `Storage`-like plus converters

Similar to `Storage`, a single native type would be used, but instead of string, it would be ArrayBuffer, since that aligns more closely to what CCF internally uses and allows efficient storage of binary data.
Since it is a custom interface there are no claims of being compatible with existing interfaces.
Converting to/from ArrayBuffer is done with converter functions.


Usage example 1:
```js
ccf.kv.msgs.set(ccf.to_int32(1), ccf.to_json({text: "foo"}));
let msg = ccf.from_json(ccf.kv.msgs.get(ccf.to_int32(1));
console.log(msg.text);
```

Usage example 2:
```js
let img = new ArrayBuffer(42);
ccf.kv.imgs.set(ccf.to_int32(1), img);
let img = ccf.kv.imgs.get(ccf.to_int32(1));
```

## Custom interface - `Storage`-like plus converters and safe keys

This is an extension of "`Storage`-like plus converters" where keys are required to have certain types which are automatically encoded in a "safe" way, without having to use a converter function.

Key encoding may look like (JS type -> native type):
- number -> float64 (yes, integers becomes floats, for best generality)
- string -> C string
- ArrayBuffer -> buffer (identity)

Usage example 1:
```js
ccf.kv.msgs.set(1, ccf.to_json({text: "foo"}));
let msg = ccf.from_json(ccf.kv.msgs.get(1);
console.log(msg.text);
```

Usage example 2:
```js
let img = new ArrayBuffer(42);
ccf.kv.imgs.set(1, img);
let img = ccf.kv.imgs.get(1);
```

## Custom interface - Type-specific functions and safe keys

This is the same as "`Storage`-like plus converters and safe keys" but using a different API and hence not `Storage`-like.
Types in function names refer to types of values: `{get,set}_{int32, int64, float32, float64, bool, string, json, arraybuffer}`.

Usage example 1:
```js
ccf.kv.msgs.set_json(1, {text: "foo"});
let msg = ccf.kv.msgs.get_json(1);
console.log(msg.text);
```

Usage example 2:
```js
let img = new ArrayBuffer(42);
ccf.kv.imgs.set_arraybuffer(1, img);
let img = ccf.kv.imgs.get_arraybuffer(1);
```

--------------------

Any variant I missed?

The above is lacking a good analysis on performance, especially towards an eye for usage with QuickJS. If needed I can add it.
