### ISSUE TITLE
Remove hints of global commit state

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1586]
We currently return a header `x-ccf-global-commit` in every HTTP response. This is deprecated and we intend to remove it. Clients can ask for the global commit version explicitly, but we do not correctly track the globally committed version that each transaction was executed on, so should not report it.

Relatedly, we are discussing removing the `get_globally_committed` method from `TxView`. We believe it is misleading - the followers' view of globally committed state can lag behind the leader's in the same way that their view of local state does. It also allows surprising state-overwrites if used incorrectly, eg:

```
auto v1 = tx1.get_globally_committed("foo");
tx2.put("foo", 42);
tx1.put("foo", v1 + 1);
```

Users should rely on session consistency or poll for their desired state to be globally committed if that's what they need, and in almost all cases should be able to operate on local state.

**Comment by achamayou** [comment]
With regards to `x-ccf-global-commit`, I suggest adding a `x-ccf-snapshot-global-commit` request header, and only generating the response header when that it is set. Once #848 is complete, we can remove this header pair entirely.

@prakashngit do you have a view on the removal of `get_globally_committed`? I think you'd mentioned before in the gitter channel that you were using it for something?

**Comment by achamayou** [comment]
@eddyashton as discussed, there is possibly a use case for an "as of last global commit" variant of read only queries, which is essentially a special case of the historical query. How that is exposed to users and to developers is up for discussion.

**Comment by prakashngit** [comment]
@eddyashton  @achamayou  Thank you for checking. Yes, we rely on get_globally_committed very much. The usage is explained below. This design was done based on CCF 0.7, not sure if there are now newer ways of achieving the same result, happy to learn:

1. Implement "eventual serializability" of writes and reads: Our write rpcs return (back to the calling application) local commit. For reads, we only want to read globally committed states. The latter then ensures that "reads respect reads" meaning that if read R2 that starts after read R1 completes, then R2 returns a version that is no older than what R1 returned. In my mind, without "get_globally_committed", the only way to implement this is to make the writes wait to return only after global commit. But this is going to incur a huge perf hit for us, since our app is write-dominated rather than read-dominated.  (please note that the writes/reads are all invoked by multiple non-interacting clients)

2. There is a second-order use case since writes return after local commit: When we process write rpcs, we insist that any state (say from other tables) that is needed to process the write rpc has been global committed. This is our way to ensuring "well definedness" of writes in "eventual serializability" . 

If there are newer features in CCF that permits implementation of the above (for non-interacting clients), I am happy to learn.

**Comment by achamayou** [comment]
@prakashngit the intention is to provide an alternate mechanism where ReadOnly endpoints can be called with a special parameter/header indicated they should be run as of the last globally committed version known by the target node, as opposed to the last locally committed version. That is effectively a special-case historical query in some sense, and seems much less error-prone than a per-key distinction inside a transaction. It also importantly removes the possibility of get_globally_committed() being called inside a write, which breaks snapshot isolation and is a very risky operation.

Would a per-Read RPC setting satisfy your first requirement still? Unless I'm mistaken, it sounds like it should.

I am not sure I understand the second use case, executing a write on the basis of globally committed state (even consistently across keys) does not lead to eventual serializability or to any serializability I can think of because it will result in some writes to those keys being ignored, which may globally commit any time, including before the write in question even completes.

**Comment by prakashngit** [comment]
@achamayou  Thank you for the notes

The proposal for per-Read RPC solves my first problem, however, it does not solve the second problem where I currently use get_globally_committed() as part of processing write rpcs. Please allow me to explain the second requirement again. Like you say, the second requirement is not a direct requirement for eventual serializability, but it is our way to ensuring "well-definedness of writes" for eventual serializability (there may be other ways). For example, say rpc_write is the method { write(A to table A) : read(B from Table B) + rpc_input }. In this example, we want read(B) to be read_globally_committed(B). If this is not the case, if for any reason global_write(B  to Table B) fails, and global_write (A to table A  succeeds), then clearly, write(A) becomes ill-defined. 

I am not sure if the above scenario ( meaning, global write (B) fails, but global write (A) succeeds) is a possibility in CCF, but as an app-developer, I err on the side of caution, and assumed that it is a possibility in CCF, and design the writes to use only globally committed read values.

**Comment by achamayou** [comment]
About read RPCs, I don't think the app would need to know. Read RPCs (ie. GETs) would support a `x-ccf-read-version: (latest|committed)` header. When this is set to `committed`, the provisioned `Tx` would consistently `get()` at what `commit_version` was set to when it was created. All reads would happen at the same version, and that version would be the latest committed as of transaction start, the application code would remain unchanged.

In the write case, the problem with reading from Table B at the last globally committed value and writing on that basis is that you may be ignoring further writes that occurred on B, but which happened before your write to A. So your write ends up being time-dependent and there's no total transaction order anymore.

```
B[k]@1 = 5   # global commit
B[k]@2 = 6   # local commit
A[k]@3 = 10 # App logic is A[k] = B[k] * 2, because global commit is at 1
```

So long as your code executes in a transaction, it is safe to read previous writes, even when not globally committed, because commit only ever moves forward: if your write to B fails to persist because the primary that was doing your writes dies before it can replicate it, then your later write to A is also guaranteed to be rolled back. Conversely, if the write to A is persisted, then the write to B was.

This isn't guaranteed across transactions of course, since an election can occur between two transactions. We do have a proposal for how it could be made to work though: https://github.com/microsoft/CCF/issues/1524

**Comment by prakashngit** [comment]
@achamayou Thank you for the notes. Thank you for the extra notes on the "x-ccf-read-version: (latest|committed) header".

Regarding the second problem, I am afraid I do not agree with the analysis above that there's no total transaction order any more. In our example, write A and write B are concurrent. Write B completes before Write A, and Write A utilizes the value of B that was from the previous write. So, when we put the serialization points that determine the total order of writes, it looks as follows: The dots represent the "global time view" for the execution of W(A) and W(B).  In the example below, W(B) starts after W(A) completes, but finishes before W(A) finishes. When we put the serialization points (shown with *), we can always put the one for W(A) after the point in the execution where we put the serialization point for W(A), and thus theoretically maintaining a total order on the writes.

W(A) :   ...............................................*.........

W(B) :       ...............................*.....

The only time we want W(A) to capture W(B) is if W(B) completes even before W(A) starts, in which case they are no longer concurrent, and W(B) is already globally committed.

So, in summary, the example above that you give is a perfectly acceptable scenario while maintaining the total order of write transactions.

My concerns about consistency and failure of write(B) leading to ill-definedness of W(A) were under the assumption that W(A) and W(B) are two separate transactions. (Exactly what you say in your last line, and perhaps this  is what you capture in 1524.?  i need to think about 1524 a bit more). 

The get_committed_globally() was a cute solution that solved all of the above, assuming that the app-developer knows how to use it.

May I kindly recommend that CCF retains get_committed_globally() for now until at least the time 1524 is resolved, and at that point, I am more than happy to work with you again to re-evaluate if is an appropriate substitute for get_committed_globally() that can be used for the implementation of eventual serializability?

**Comment by eddyashton** [comment]
I'm closing this issue, as the intended topic (described in the title) of removing `x-ccf-global-commit` has been completed in #2144.

I've opened #2160 to discuss replacements for `get_globally_committed`, as we still intend to deprecate this.

@prakashngit I'm afraid I still don't fully understand your write use case. While it is true that global commit will only move forward, it can still and move in arbitrarily large steps, losing intermediate writes. Any write transaction which operates on a global-read is reading non-deterministically old state, and discarding everything in the interim - is that really what you want?

In summary:
1) For your read-read case, we're discussing potential solutions in #2160. We may not find a clean way to implement this in the framework, in which case it is the responsibility of the client - if it doesn't want to reveal a read A which may be rolled back, it must poll until A is committed before revealing it.
2) For read-writes, I think your core concern is this: "if for any reason global_write(B to Table B) fails, and global_write (A to table A succeeds), then clearly, write(A) becomes ill-defined". This is not possible in CCF. If A occurs after B, and thus may have read B's writes, it can only commit if B also commits. The local, non-globally committed state forms a chain, and either it is all rolled back on election or it commits. So this kind of ill-defined write is not possible, and does not need to consider global commit.

Please continue this discussion in #2160, and let us know if there's a use case we're not considering.
