### ISSUE TITLE
Careful vote serialization does not handle special characters

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1687]
The JS modules e2e test currently uses the simple voting mechanism (`return true`).
The proposal body for deploying JS apps contains JSON object keys starting with `/`, which is not handled properly when using careful votes. The generated votes contain code like `if args.bundle.metadata.endpoints./compute == nil`. Using a different syntax that can handle special characters probably makes more sense.

The reason I'm using careful votes is that I'm extending the `infra/` code to allow deploying a JS app bundle on start up. For that I'm adding a new method to `Consortium` and all existing methods use careful votes, so I figured I have to comply. Does it even make sense to use careful votes for JS app deployments? It would mean that the source code of all modules is replicated in each vote.

**Comment by eddyashton** [comment]
Looking into this now. The lookup is fine, we replace `.endpoints./compute` with `["endpoints"]["/compute"]`. This threw up some issues with the construction of lua literals that I've also fixed (the `modules` list-of-objects is a more complicated struct than we'd needed to handle previously). However I'm still hitting odd errors with the careful vote: it seems the module script has gained a phantom newline at its start in the proposal, so direct string comparison doesn't work, and after working around that I'm still getting a mismatch between the expected object-table and the one we actually see.

I'll debug this a little further, but don't want to spend too long on it since we intend to replace the Lua governance scripts with JS.

Trying to construct Lua code from Python that compares a JSON-object-converted-to-Lua with a Lua literal of what we expect that to look like, is an odd thing to be doing in the first place.
