### ISSUE TITLE
Mirror install tree layout in build tree

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1776]
This will simplify a bunch of scripts that have path detection logic for working against an install vs build/dev tree. A concrete example is the invocation of `sandbox.sh` and related arguments like `--binary-dir`.

**Comment by achamayou** [comment]
A very cheap way to do that would be to create two symlinks in cmake:

`bin -> .`
`lib -> .`

This may or may not cause various instances of directory-traversal logic to have a fit of course.

**Comment by achamayou** [comment]
@letmaik just to check, it this just `sandbox.sh` only, or is there more?

**Comment by letmaik** [comment]
`sandbox.sh` and any script that calls it. I'm not aware of other cases.

**Comment by achamayou** [comment]
Ok, so, @jumaffre pointed out that we could tell cmake to structure the build dir similarly to install: https://stackoverflow.com/questions/6594796/how-do-i-make-cmake-output-into-a-bin-dir/6595001#6595001

A couple of thoughts though:

1. This is nearly as much code as we would save from sandbox.sh
2. For it to work for projects that use CCF (and sandbox), they also need to pick it up. So they either need to not forget to add this boilerplate, or we preemptively set it in common.cmake and change their build layout whether they like it or not.

I am not convinced that this is a reasonable improvement over the status quo, especially because of 2. Keeping a moderate (<10loc) amount of logic in `sandbox.sh` so CCF users can stick with common cmake defaults seems acceptable to me.

**Comment by letmaik** [comment]
I don't mind how `sandbox.sh` looks like, but I do mind how https://github.com/microsoft/CCF/blob/57a990f25558ae52048347e79c99aed9685bdd7d/samples/apps/forum/test/util.ts#L31-L43 looks like.

**Comment by achamayou** [comment]
I don't this outweighs pushing a cruel and unusual restriction on build and install matching on all downstream projects. It's nice that we auto-compute this path for users of that sample rather than tell in the doc to set their $PATH when running a sample from the build/ directory, but it's not worth such an extensive change.
