### ISSUE TITLE
AFT: Support reconfiguration

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1852]
This is the top level ticket for reconfiguration. This will be broken down into multiple tickets and PRs.

- [ ] Change the BFT node_id to be the same as in CFT. To do this we will need to keep a node_id -> ordered_id mapping and have a data structure that can allow us to deterministically decide which node is the primary in any given view within a configuration.
- [ ] Change BFT to use replica ids which have the same NodeIds that are derived from the public cert like CFT

**Comment by jumaffre** [comment]
As discussed with @ashamis and @achamayou and follow-up from #2241: we still use monotonic node IDs in BFT so that the primary node ID in a given view can be computed deterministically by all nodes in the network. Once reconfiguration works in the BFT variant of the consensus (and we can skip nodes during a view change, so that a new added node doesn't try to become primary when it is just added), we should change the node IDs in BFT to also be the hash of the node's public key.
