### ISSUE TITLE
Snapshots may be larger than ring buffer maximum message size

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#1858]
As a CCF service processes more transactions which write to different tables at different keys, snapshots may grow without bounds. Currently, when a snapshot is generated, it is written to the outbound ring buffer in one go. It might be split into fragments if it is too large but if it actually is larger than the maximum message size (`--max-msg-size` option to `cchost`), the CCF node will crash, e.g. (with `16777216` the default maximum message size):

```
2020-11-04 15:22:18.596 | ERROR    | infra.remote:log_errors:86 - Contents of /home/lyshi/repos/CCF/tests/workspace/recovery_0/err:
terminating with uncaught exception of type std::logic_error: Requested a write of 16827539 bytes, max allowed is 16777216
```

To solve this, we could just bump the default maximum message size but this just pushes the problem further. The solution to this should work for any snapshot size, however large it is. Instead, we could either:
- Split the snapshot into multiple chunks before writing it to the ring buffer.
- Build a enclave<->host large message system which lets the enclave directly write to host memory, bypassing the ring buffer altogether. This would involve allocating a sufficiently large buffer on the host to store the snapshot. It seems that this solution should only apply to snapshots as other ring buffer writers already chunk messages into smaller bits (e.g. TLS). 

**Notes:**
- This issue should not affect services with small key-value store footprint, e.g. services that write to a few tables and/or a few keys. 
- To reproduce this issue:
```bash
$ TEST_ENCLAVE=virtual python recovery.py --gov-script CCF/tests/gov.lua --use-snapshot --snapshot-tx-interval 1000 --msgs-per-recovery 1000000
```

**Comment by eddyashton** [comment]
Splitting the snapshot message into multiple chunks so that it never exceeds the maximum message size is the simpler solution from an implementation perspective, but still requires the enclave thread to be blocked for a long time writing these chunks, and likely saturates the host thread that is reading those chunks for a long time. Since we cap the amount of data that the host can read each UV tick, this processing may cause a noticeable delay on any other work in the service.

There's a few ways we could work with a host-memory buffer. Ideally we'd be able to allocate it on-demand, inline, but this is likely to require an OCall. We could have a ringbuffer message roundtrip to request an allocation, but this means producing the snapshot later, or at least maintaining it in memory _now_ so we can copy it to this allocated block later. A workable compromise might be to try and pre-allocate a snapshot buffer, regularly requesting (asynchronously) a buffer that we _believe_ will be 'big enough' for the next snapshot, so that when we get to snapshot production we _probably_ have a host-memory buffer ready to use. If we don't we could take a slow-path OCall here. This needs some thought around synchronisation - assume the enclave is only ever producing a single snapshot, host needs to signal it has finished with a buffer or give the enclave a new one before the next enclave can be written.

For the _inbound_ snapshot (ie - during recovery, passing the file-read data from host to the enclave), we should be able to pass a small message pointing to a host-owned buffer, and (thanks to snmalloc) free this from within the enclave once we're finished with it. However, we probably still need to copy this into the enclave before processing it, to avoid TOCTOU attacks.

**Comment by achamayou** [comment]
I'm very keen to try the basic approach of chunking the snapshot and sending it over the ring buffer, even if it means increasing the max message size as well as some performance hit on the thread producing snapshots. The additional complexity involved in other approaches may not be warranted for the kind of state sizes we're dealing with now, and would likely tie us to implementation details of our current TEE.

**Comment by jumaffre** [comment]
As discussed today at standup, splitting large snapshots in the snapshotter to work around the maximum ring buffer message size isn't the most sensible option. Instead, we discussed:
- Removing the cap on the maximum message size so that any messages (however large they are) are successfully passed to the ring buffer writer on write.
- Adding a outgoing (capped) message queue in the enclave (similar to the `non_blocking` writer factory for incoming messages on the host). This should be fine with regards to memory growth as messages (e.g. snapshots) are already held in the enclave memory before being sent to the host. This has the implication that the enclave shouldn't process incoming messages if its outgoing queue is full (backpressure). 

The size of the outgoing message queue should be configurable by operators. We could also keep track of the total serialised KV size to inform operators when it is close to that limit.

**Comment by achamayou** [comment]
Discussed with @eddyashton yesterday: CCF could decide, once snapshots reach a certain size thought to be detrimental to the operation of the system (ie. too large to be written out, large enough to threaten to fill memory available to the enclave), to enter a new SUSPENDED service state.

A SUSPENDED service would reject all user transactions, or at least all user writes. The argument for all user transactions is that historical queries can also result in large allocations (#3234).

A governance operation (transition_service_to_open) would be required to unsuspend the service, giving the consortium time to address the situation without having to resort to a disaster recovery.

Using the snapshot size as a proxy for memory usage is not perfect, but is simple and comparatively inexpensive at runtime.

**Comment by jumaffre** [comment]
As discussed with @eddyashton, using new ring buffer messages for the enclave to request a host buffer of a certain size seems like the best way to go for now, as the enclave and host currently share the same memory space on all platforms:

Rough sequence diagram:
```mermaid

sequenceDiagram

participant Host
participant Enclave

Enclave->>Enclave: Take store snapshot at seqno N
Enclave->>Host: [NEW] Request buffer with size S = snapshot serialised size
Host->>Host: Allocate buffer of size S
Host->>Enclave: [NEW] Pointer to buffer of size 
Enclave-->>Enclave: On SGX, sanitise buffer
Enclave->>Enclave: Serialise snapshot at N
Enclave-->>Host: Writes serialised snapshot at pointer
Enclave->>Host: [NEW] Notify that snapshot has been written
Host->>Host: Write snapshot file
Enclave->>Enclave: Snapshot evidence is committed
Enclave->>Host: Writes snapshot receipt on ring buffer (existing)
```

Notes:
- The enclave will need to keep track of each host buffer request so that multiple in-flight snapshots don't override each other.
- We could make use of memory-mapped files on the host so that the enclave writes directly to the file.
