### ISSUE TITLE
lowerCamelCase in REST API

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1940]
Part of https://github.com/microsoft/CCF/issues/1918.

"JSON property names SHOULD be camelCased..."

"All identifiers including namespaces, entityTypes, entitySets, properties, actions, functions and enumeration values SHOULD use lowerCamelCase." -> mostly in URLs

CCF uses its own set of macros to define JSON types from structs and already supports providing different field names during serialisation/parsing, e.g. with `DECLARE_JSON_REQUIRED_FIELDS_WITH_RENAMES`. An alternative would be to automate this and auto-camelCase field names to avoid too much repetition / boiler-plate.

**Comment by eddyashton** [comment]
On JSON property names:

I think we're consistently `snake_case`, which is better for the end-user than many existing Azure service's mixed-case. Personally I like grepping `my_field` and finding every instance in C++ _and_ JSON _and_ the Python/JS that's using it, rather than having too many trivial renames.

So although we can support this, and could even do it automagically (ish), I vote for staying consistent on the current field names.

**Comment by achamayou** [comment]
As discussed and agreed in the team, the benefits of maintaining existing codebase consistency in the SDK outweigh alignment with an Azure SHOULD guideline in this particular instance.

User-defined endpoints remain free to use the convention they prefer, since they control URL paths, content type and KV serialisation.
