### ISSUE TITLE
Use client proxy to send requests to pbft

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#199]
PBFT has a client proxy that broadcasts requests to all replicas and implements the reply logic of the pbft client. This needs to be configured in ccf so that requests get redirected to the client proxy.

**Comment by jumaffre** [comment]
I believe that most of this issue is now completed, as implemented by https://github.com/microsoft/CCF/pull/220 and https://github.com/microsoft/CCF/pull/263. PBFT's client proxy is used to send requests to PBFT from CCF. When a reply is ready, PBFT calls the client proxy's `recv_reply()` callback that will respond to the client based on the `RequestID` assigned by CCF.

We should still test the behaviour with multiple replica but I would be keen to close this. @olgavrou, @achamayou, thoughts?
