### ISSUE TITLE
KV should serialise governance tables as JSON

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#1993]
Currently, the default is to serialise all tables as msgpack. For easier auditing and interoperability with JS, we'd like to default to JSON - at least for our governance tables and perhaps for (almost) everything. Some tables may need faster serialisers for rapid lookup, such as from caller's DER to caller ID.

There's an incomplete PR attempting this, with several unexpected but seemingly required additions, here: #1860.

**Comment by achamayou** [comment]
After discussion with @syhamza, there's interest in getting at least the signature and nodes tables to a stable, auditable state as soon as possible.

Some thoughts on Signatures:

1. Most fields are well-suited to the conversion with little performance hit
2. The root of the tree needs conversion to hex, to be consistent with our representation of digests throughout the API.
3. Storage of the tree snapshot is a very poor fit, since it's a large binary blob. I think we can split it to a separate table (public:ccf.internal.tree), and write it raw. This isn't totally trivial, some checks we have on signatures will need adjusting, but I'm exploring the impact.

@jumaffre @eddyashton, feedback welcome. I'll look at the nodes once I'm done with signatures.

**Comment by jumaffre** [comment]
For the serialised Merkle tree in the signature tx, two of the main impacts I can think of are:
1. When applying a snapshot, we assume that the snapshot was taken at the `seqno` of a signature, which means it is safe to read from the signatures table after applying the snapshot, and seed the new history with the serialised Merkle tree contained in the signature. 
2. For historical queries, we deserialise the Merkle tree contained in the signature to find out if the target tx is indeed validated by that signature.

I think both would be fine with a separate table, as long as the serialised Merkle tree is written to the store at the `seqno` as the signature.

**Comment by achamayou** [comment]
Yes, writes would occur in the same transaction of course.

**Comment by achamayou** [comment]
Dupe #2237
