### ISSUE TITLE
Automatic ledger rekey on node retirement

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2078]
Currently, when nodes are retired, the ledger secrets are not automatically refreshed. This means that the retired node still has access to the encryption key required to decrypt the ledger entries past the `seqno` at which that node is retired. In other words, if the retired node is malicious, it could still read the private ledger entries past its retirement. 

This is currently mitigated by the `rekey_ledger` proposal (see [docs](https://microsoft.github.io/CCF/master/governance/common_member_operations.html?highlight=rekey#rekeying-ledger)) but this is a manual operation involving member actions. Ledger rekey could easily be enforced by the framework automatically on node retirement.

**Comment by achamayou** [comment]
We cannot do this atomically, because a retired node may be a necessary part of the quorum to commit the signature following a reconfiguration, and therefore the reconfiguration itself. It's not until the transaction that sets the node to REMOVED (see #1713) has committed that the rekey can safely take place.

I think the REMOVED transaction may be a good place to execute the rekey, since a node for which retirement has been committed should never need to read transactions past REMOVED.

**Comment by jumaffre** [comment]
As discussed with @achamayou, this can only be done during a code upgrade, when the last "old" node is retired. This is because all enclaves with the same measurement are considered equal and so rekeying the ledger for each node retirement is unnecessary, and so wasteful.

Moreover, a single compromised enclave version would also leak the service identity private key, which would allow a malicious actor to craft new ledger transactions, issue receipts, etc. When there is suspicion that a node measurement has been compromised, the best solution is to perform a disaster recovery procedure.

**Comment by achamayou** [comment]
We don't think there is a benefit to doing this, because in the event of a known node compromise, the only safe action to perform is a DR. Careful members should still rekey the ledger periodically, to mitigate the confidentiality impact of such a event.
