### ISSUE TITLE
Reported term of read-only tx just after election is incorrect 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#2224]
As discussed with @eddyashton today, for read-only requests (typically `GET`), we currently report the `Tx`'s `term` (retrieved via `tx.commit_term()`)  in the HTTP response header. The `Tx`'s term is set on the `store` on rollback (when becoming primary or backup), to the consensus term to which we rollback to. 

However, the very first read-only `Tx`(s) issued by clients right after the election will report the wrong `TxID` as it will report the `seqno` of the last entry in the now-finished term, but with the _current_ term at which the transaction was executed.

This was identified when looking at (almost) unrelated [issue in the CI](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=19316&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded&l=9803) and summarised here:

```
// seqno 129 is the last entry committed in term 4

// Killing primary
46: 13:20:59.428 | SUCCESS  | suite.test_requirements:wrapper:19 - Stopping current primary and waiting for a new one to be elected

// New primary 6 is elected in term 6...
46: 13:21:04.502 | INFO     | infra.network:find_primary:730 - [3||] GET /node/network
46: 13:21:04.502 | INFO     | infra.network:find_primary:730 - 200 @6.129 {"current_view":6,"primary_id":6,"service_status":"OPEN","view_change_in_progress":false}

// But @6.129 isn't a valid TxID!
```

In other words, if the user were to pass `6.129` to the `tx/status` endpoint, the result would come back as `Invalid`. 

Instead, the consensus should inform the store of the `term` of the `idx` at which it rolls back. The store should keep track of this "read term" and use it when a `Tx` grabs its `read_version` and `term` (implementation details deliberately vague for now, but it seems feasible in practice). 

Bundled with this change should be a slight refactoring of the `frontend.h` logic (see below) which has been prone to confusion and a source of multiple bugs. Instead, encapsulating most of the commit version/term logic in the `Tx` would be preferable (easier to write unit tests for it, etc.): 
https://github.com/microsoft/CCF/blob/7b6b60780dd55d53546e490596a4834b124d149e/src/node/rpc/frontend.h#L291-L300

**Comment by achamayou** [comment]
Unless I'm missing something, I think the store can just keep its "old term" on a rollback as the read term for version < rollback index, I don't think the consensus needs to provide any information other than what it does now (the new term on rollback).

**Comment by eddyashton** [comment]
> Unless I'm missing something, I think the store can just keep its "old term" on a rollback as the read term for version < rollback index, I don't think the consensus needs to provide any information other than what it does now (the new term on rollback).

I think the complication is that you can roll back multiple times to the same point in an old term. So the last written value you have is `2.10`. When term 3 starts, you rollback to `2.10` - this is fine, its the term you already had as you say. Then you get `3.11` and `3.12`, and your "current term" (what you're both reading and writing in) are `3`. But these don't get committed, and there's a rollback again - you need to know that as well as rolling back to `10`, this is `2.10` not `3.10` (and the next thing you'll receive is `4.11`).

**Comment by achamayou** [comment]
You will need to store a (read_term, version), so you can compare on read Tx to decide which term to report. I think you only ever need one, and if you have already for the index you are rolling back to, you don't need to/should not replace it.

@2.10
rollback(10, 3) -> capture (2, 10) as "previous_term_end"
read tx reports 2.10 because read_version <= previous_term_end.read_version
@3.11
@3.12
read tx reports 3.12 because read_version > previous_term_end.read_version
rollback(10, 4) -> "previous_term_end" unchanged, because previous_term_end.version == 10
read tx reads 2.10 because read_version <= previous_term_end.read_version

So it seems fine?

**Comment by eddyashton** [comment]
As far as I can tell, I think these approaches are basically equivalent? But I don't have a complete model of either.

I agree that we only need to store a single additional `Term` for this, not multiple entries. I think we should snapshot these in the `Tx` rather than adding comparison logic of which to report later.

My model is that the `term` we currently store in `Store` (and pass to each `Tx` when it asks "where should I read?") is really a _write term_ - the term in which any new entries would be written, which matches the latest term the consensus has advanced to. Beside this, we need a _read term_, which pairs with the `version` to always give the transaction ID of the end of the roll. Whenever we add an entry, we update `read_term = write_term`. When we rollback, we need to reset `read_term` to match our new end-of-roll transaction. I'm sure we can remember this somehow, but the simplest solution I see is that the consensus can just tell us this when it tells us to rollback - it already has this information authoritatively, and is telling us everything else.

**Comment by jumaffre** [comment]
I thought about this a little more and I believe there's an alternative approach where we move the point a `Tx` grabs its `read_version` out of `Tx::get_handle_by_name()` to its creation via `store->create_tx()`. In `create_tx()`, the store then also asks the `consensus` what term/view is associated with this `read_version` and records this in a new `Tx`'s `read_term`. On `Tx`'s `commit()`, if the transaction is read-only, we set the `Tx`'s `version` to `read_version` and the `commit_term` to `read_term`. Then, the frontend logic becomes:

```C++
auto cv = tx.commit_version(); 
if (cv != kv::NoVersion) 
{ 
  ctx->set_seqno(cv); 
  ctx->set_view(tx.commit_term()); 
} 
```
I believe this also covers the case of long-running read-only `Tx`s that possibly span across multiple terms/rollbacks (which I believe should still return a valid result?). 

There's still an issue though: what if the `read_version` of the `Tx` still hasn't been passed to the `consensus` (i.e. it's in the ordering pipeline in `Store::commit()`)? If in `store::create_tx()` the `consensus` didn't know about `read_version`, we can infer that `read_term` is the current `Store`'s `term`?

It feels too simple though - what am I missing?
