### ISSUE TITLE
Documentation for internal tables

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#230]
As well as being prefixed (#140), framework tables (ie. starting with `ccf.`) ought to be documented:

1. Schema
2. Access category
3. Description
4. Serialisation format

**Comment by achamayou** [comment]
To start with, governance tables that are expected to be audited by users should be documented.

**Comment by CH-ND-N** [comment]
r I am interested please assign this to me. I am new to this but have knowledge of C, C++, and proper markdown knowledge.I will need guidance.

**Comment by achamayou** [comment]
@CH-ND-N thank you for helping, may I suggest you start by reading the “Governance” section of the online documentation, before having a look at member_frontend.h? That’s where most of the logic interacting with internal tables lives. If you have any questions, please do not hesitate to ask!

**Comment by jumaffre** [comment]
Assigning this to myself as I've been looking into (in the background for now). Ideally, we would automatically generate the documentation from the existing definition of CCF's built-in tables. Doxygen annotations is probably the best option I can think of.

**Comment by lynshi** [comment]
Bumping this since it's a little more useful now, as we're querying the CCF tables in our endpoints, and I ended up here while searching for schemas (incidentally, tables are defined [here](https://github.com/microsoft/CCF/blob/main/src/node/network_tables.h), and you can follow the types to infer the schemas). @eddyashton has also mentioned having C++ APIs wrapping table querying to decouple application code from schema changes, which seems even more useful than a published schema.

**Comment by achamayou** [comment]
All governance tables are documented now, but still TODO:

- [ ] document internal tables
