### ISSUE TITLE
Invalid Entity Id Error When Submitting a Proposal

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#2353]
**Describe the bug**
When a proposal is submitted by an active member, we get the following error:
```
400 {\"error\":{\"code\":\"InvalidInput\",\"message\":\"At #/: Entity     id should be hex-encoded string: null\"}}\n"
```

**To Reproduce**
1. Start a CCF network.
2. Use a client for the member that only uses signature authentication.
3. Make the member active (ack the state digest).
4. Submit a proposal to open the CCF network with the active member.

**Expected behavior**
The proposal is submitted successfully.

**Environment information**
CCF 0.19.3

**Additional context**
The submitted proposal is as follows:
```
tables = ...
service = tables["public:ccf.gov.service.info"]:get(0)

if service.status == "OPEN" then
    return empty_list()
end

return Calls:call("open_network")
```

There is no entity id involved here, so the error is likely happening when CCF does member validation (e.g. when checking to see if the member is active). 

In the ledger file, we have the following contents:
![image](https://user-images.githubusercontent.com/9373058/112370404-935b0480-8c9a-11eb-99e1-6ef95545bbb1.png)

Note how `key_id` in the signed request is an empty string. However, the key id is present as part of the request and is shown in the above image between the question marks.

However, later on we do see `key_id` populated correctly in the `acks` table.
![image](https://user-images.githubusercontent.com/9373058/112370811-13816a00-8c9b-11eb-807e-1c07fb6594bd.png)

@achamayou has the full ledger file from the primary node for a network in which we observed this issue.

**Comment by eddyashton** [comment]
The empty entries are what we expect in the ledger (though we didn't _know_ that's what it was doing, and obviously it looks wrong, so we'll fix it - tracked [here](https://github.com/microsoft/CCF/issues/2356)).

So we don't think that's where the parsing error is coming from. We'll continue investigating.

**Comment by achamayou** [comment]
@lynshi the issue comes from this part of the constitution you are using:

```
  -- operators proposing operator changes can pass them without a vote
  if operator_change and is_operator(tonumber(proposer_id)) then
    return PASSED
  end
```

`tonumber(proposer_id)` attempts to convert the proposer_id, which is now a hex string, to a number. That fails, returns `nil`, which is then given to `is_operator`:

```
  -- defines which of the members are operators
  function is_operator(member)
    member_info = tables["public:ccf.gov.members.info"]:get(member)
```

That tries to turn `member` into a valid EntityId for the lookup, which is where the validation failure occurs.

The proximal fix is to change the line to:

```
  if operator_change and is_operator(proposer_id) then
```

as in the sample: https://github.com/microsoft/CCF/blob/main/src/runtime_config/operator_gov.lua#L120

This change was part of #2279, and probably ought to have been highlighted in release notes. The chance that this particular class of issue will occur again should be quite low once the governance refactor is complete, since we will aim to keep it compatible, and error messages will be more accurate in general. It doesn't become impossible however, and @eddyashton has proposed some ideas that would help.

In the near future, we are focusing on the transition to the JS governance. We will keep this in mind, and come back to it once the refactoring dust has settled.

**Comment by lynshi** [comment]
Ah, thanks for the catch! Sorry about that, it was an oversight on our end when we did the upgrade.
