### ISSUE TITLE
Do we really need a `lfence` after `oe_is_outside_enclave`?

### ISSUE THREAD

**Issue by LuminousXLB** [microsoft/CCF#2410]
Hi

I was reading the code of this project and found that we have a `lfence` after some `oe_is_outside_enclave` [here](https://github.com/microsoft/CCF/blob/main/src/enclave/main.cpp#L120).

According to the discussion in https://github.com/openenclave/openenclave/pull/3418 , this seems to be unnecessary and can be done by clang or lvi-mitigation automatically.

Do we really need this manual mitigation at present and is it secure to remove that?

**Comment by achamayou** [comment]
This was added in response to https://github.com/microsoft/CCF/pull/1492#issuecomment-673018395

My understanding of the intention expressed by @douglasmaciver (also reflected in the discussion you link to) is to provide this protection in sensitive areas _even_ if the code isn't built with LVI mitigations. CCF binary releases and default build configuration include those mitigations, so this is generally redundant unless users go out of their way to build without mitigations.

Since the only instances of this are on setup ecalls, which happen once at startup, performance is not concern.

**Comment by LuminousXLB** [comment]
> This was added in response to [#1492 (comment)](https://github.com/microsoft/CCF/pull/1492#issuecomment-673018395)
> 
> My understanding of the intention expressed by @douglasmaciver (also reflected in the discussion you link to) is to provide this protection in sensitive areas _even_ if the code isn't built with LVI mitigations. CCF binary releases and default build configuration include those mitigations, so this is generally redundant unless users go out of their way to build without mitigations.
> 
> Since the only instances of this are on setup ecalls, which happen once at startup, performance is not concern.

Thanks for your reply.

Thus this is a redundancy, but since this slice of code is not intensively called, it's ok to leave it redundant and to provide a stronger security guarantee. Is that right?

**Comment by achamayou** [comment]
@LuminousXLB yes, that's right.
