### ISSUE TITLE
Give `apply` more control over KV, including current proposal

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#2454]
During proposal evaluation, we take a local copy of the proposal info in C++, modify it as we progress, and finally put it back in the KV. This means that the `apply` function we call in JS does not see these modifications, and potentially and modifications _it_ makes are overwritten. For consistency, we should ensure everything is in the KV before calling a governance function which may see it.

Note from PR:

The use case we currently have is "`apply` may modify _every other_ proposal", but this is only a hair's breadth from "`apply` may modify _this_ proposal", and I think we should respect that modification here.

I'd like to audit anywhere else we may have this pattern of a long-held local copy of the KV value - we may need to `put` before `JS_Call`, and then `get` again afterwards.

_Originally posted by @eddyashton in https://github.com/microsoft/CCF/pull/2443#r610718875_

**Comment by achamayou** [comment]
I think we were doing that because the state of the proposal could change until after `apply()` was, well, applied. In cases where `apply()` failed, we captured and stored the output in the proposal. But now that this class of error triggers a discard, it should be safe to store the state of the proposal in the tx _before_ we call `apply()`.

I do not think there is a reasonable implementation of `apply()` that writes to the proposal table, but I suppose that's for the consortium to decide. An implementation that observes the proposal state is also difficult to imagine, but not inconceivable.

**Comment by achamayou** [comment]
As discussed, another approach would be to scan the write set after `apply()` and if it has written to `proposals`, reject it. Or to give constitution call a read-only view of that table.

**Comment by achamayou** [comment]
We don't think this is necessary at the moment.
