### ISSUE TITLE
js: Date.now() returns 0

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2468]
Trying to get insecure host time in JS via `Date.now()` returns `0`.

I'm not sure why this is happening. quickjs uses `gettimeofday()` which is listed as supported in the [OE docs](https://github.com/openenclave/openenclave/blob/master/docs/LibcSupport.md) (time is part of the [default OCALLs](https://github.com/openenclave/openenclave/blob/52b065d0b8fb652d8c919a47a99411aa46ab9f6d/include/openenclave/internal/calls.h#L86)).

EDIT: quickjs also uses `localtime_r()`
EDIT2: For this to work reliably, time would have to be "deterministic", meaning it is constant within a transaction and stored, such that re-doing a transaction (in case of conflict or similar) uses the same time.

**Comment by eddyashton** [comment]
You need to opt in to get this OCALL from OE, and we don't (because we don't want surprising OCALLs in the middle of our code). We provide a stub `gettimeofday()` in `stub_time.c`. We do have time from the host (`enclave_time.h`) that we _could_ use here, but converting that to standard time is not yet done. And in general we don't want to pretend we have trusted time, and its one of the (many) bits of a 'standard' programming environment that we generally want to tell people "your in an enclave - this doesn't do what you expect".

**Comment by letmaik** [comment]
After thinking about it a bit more I think exposing a separate function is ok. Any library that validates time always accepts a specific time as well (e.g. jsrsasign). Date/time libraries like Moment.js also accept a custom time to be parsed and then further modified. `ccf.getUntrustedTime()` returning a UNIX timestamp seems good enough.

**Comment by eddyashton** [comment]
I think enforcing a single time value to reduce non-determinism is the wrong approach.

Apps in both C++ and JS can already access non-deterministic things in their execution (the currently executing node ID, calling `random()`, surely many others). These will break in BFT, but I think the fix for that has to be (a) an explanation that you _can't_ put these directly into the KV in a Byzantine configuration, with (b) some way to capture those non-deterministic values and access them in re-execution. But even when we can capture them, I think hiding those non-deterministic values behind existing APIs is going to be more work than its worth (with difficulties like that noted above of no context object, requiring an implementation that reads from some thread-local pre-stored value?).

A use case that we've had requests for and believe we can now support in C++ is "time how long my endpoint took", by getting different 'now' values at the start and end of your handler. Sure the framework does some processing around this that wouldn't be counted, and it doesn't include retries, and so on, but you can get a reasonable answer for "how long does it take me to generate 1000 new keys". I think we should also support that use case in JS.

**Comment by achamayou** [comment]
@letmaik ok, would we leave Date.now() as it is, or remove it/make it throw?

@eddyashton Like I said, I think we can patch this one to have access to the context easily. I think we could attempt to do the same for random and for node id. We could clearly namespace what's deterministic from what's not (or even offer deterministic variants for some stuff with documentation that says "if you want to do this and have it work with BFT, make sure you call the deterministic API for it"). Perhaps I am too optimistic here, but it's not obvious to me that madness lies this way. I think I could imagine a situation where carefully patching a few things means 95% of handlers "just work" with BFT?

To your second point, we already know we can't do the start time like that because of re-execution. The second one could be get_untrusted_host_time() as opposed to get_untrusted_deterministic_host_time()? The semantics of elapsed time captured that way in a BFT setting are pretty shaky anyway.

**Comment by letmaik** [comment]
@eddyashton, @achamayou and myself had an offline discussion and came to the following conclusion:

- The local timezone of `Date.*` functions is assumed to be UTC-0.
- Endpoints (via `app.json`) can opt-in to a specific `Date.now()` behaviour via a new `"time"` field (or similar):
  - (default) `disabled` - `Date.now()` is disabled and throws an error
  - `untrusted_host` - `Date.now()` returns untrusted host time from the node.
 
In the future, there may be more options. How BFT-compatible time is exposed is out of scope for now. It may be another option or a separate API.

The proposal above relies on some quickjs patching to swap out the default time implementation, likely by having a new time callback function in `JSContext` that can be set via a new API.

**Comment by achamayou** [comment]
This is just to register one more instance of user interest for the proposal outlined by @letmaik in his latest comment.

In addition, a suggestion of a leader-issued, follower-validated time was made, akin to the way signatures work. It's unclear exactly how that would work in the face of network delays, and what the exact security guarantee would be, but it is perhaps worth exploring.

**Comment by achamayou** [comment]
While we do not want to maintain a substantial fork, we also are producing our own build anyway, so a limited patch (which we have done for quickjs also) is not out of the question.

**Comment by achamayou** [comment]
Not going to add substantial new user APIs before container re-design.
