### ISSUE TITLE
Metrics don't include JS endpoints

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2636]
`/node/api/metrics` does not include any JS endpoints.

Sample output after many calls to a JS app:
```json
{
    "metrics": [
        {
            "calls": 1,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "api/metrics",
            "retries": 0
        },
        {
            "calls": 8,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "local_tx",
            "retries": 0
        },
        {
            "calls": 2,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "network",
            "retries": 0
        },
        {
            "calls": 1,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "network/nodes/self",
            "retries": 0
        },
        {
            "calls": 1,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "network/nodes/{node_id}",
            "retries": 0
        },
        {
            "calls": 1,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "state",
            "retries": 0
        },
        {
            "calls": 20,
            "errors": 0,
            "failures": 0,
            "method": "GET",
            "path": "tx",
            "retries": 0
        }
    ]
}
```

**Comment by achamayou** [comment]
So:

1. `/node/api/metrics` is only metrics for `/node/*`, you want `/app/api/metrics` for app (including js) endpoints
2. There is a bug still (repo in https://github.com/achamayou/CCF/pull/new/js_metrics_investigation), which is that js endpoints are prefixed with "/" for some reason, and I will look into that.

**Comment by achamayou** [comment]
In js_generic, we always prepend a "/" to the method: https://github.com/microsoft/CCF/blob/main/src/apps/js_generic/js_generic.cpp#L492

But for native endpoints, we not only don't prepend, but also strip the leading "/" if it's there: https://github.com/microsoft/CCF/blob/main/src/endpoints/endpoint_registry.cpp#L206

It seems to me that:

1. this is mad
2. we should align js behaviour (not prepend, strip if present) and samples (do not prepend /) on C++.

@letmaik, @eddyashton thoughts?

**Comment by eddyashton** [comment]
I agree it should be consistent, but think it should always be prefixed. Its unprefixed in a bunch of C++ endpoints for historical reasons (it used to be a JSON-RPC command called "foo", and we didn't do a pass renaming them all to "/foo"). But since these are now HTTP paths, they should all be "/foo", as they are in the HTTP request line and the `app.json` definition. Then the code would be "we assume the `/` is here and don't strip or prefix it at any use point", apart from an addition to the C++ `install()` path which prefixes if its not present, for backwards-compatibility (not forcing apps to go modify all their `install()` calls).

**Comment by achamayou** [comment]
Ok, I think what's important in my mind is:

1. Consistent across JS and C++
2. Backwards-compatible for C++, because that's where we have the most production users now.

I think your proposal is nearly backwards-compatible, except for the fact that it will change the metrics: users registering "log/private" will start to see the endpoint stats for "/log/private" instead of "log/private".
