### ISSUE TITLE
CCF's kv should expose Values as well as Maps

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#274]
We keep finding situations where we the kv to store a single value of a certain type, rather than a map of several values. The current solution is to create a `Map` from `size_t` to the value type, and only ever access the value at key `0`. This is an ugly paradigm to expose to app writers.

Instead, the kv could expose a `Value` type, parameterised only by a `TValue` and no `TKey`. Under the hood, we can implement this as a wrapper around a `Map`, either keyed by a `size_t` or a single-value struct.

**Comment by eddyashton** [comment]
I also found a case where I really wanted a _set_, where I only cared about the existence of keys and not their corresponding values. I think we can support this similarly, with a `kv::Set<T>` type wrapping a `kv::Map<T, Mono>` (cf `kv::Value<T>` as `kv::Map<Mono, T>`), where `Mono` is probably a handmade single-valued type or perhaps `nullptr_t`.

**Comment by achamayou** [comment]
@eddyashton looking at this in the post-flat-KV and JS apps world, it seems to me that:

1. This can be implemented completely in user space as either a C++ or JS wrapper (or indeed, both).
2. There is not much we can do at the framework level to support this, if we really want to keep serialisation user-defined and not tag values.

So I'm tempted to conclude that resolving this issue is a matter of proving (and using) a sample wrapper? Am I missing something?
