### ISSUE TITLE
Docs incorrect about transaction read keys

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2751]
https://microsoft.github.io/CCF/main/audit/ledger.html
--> includes actual read keys

https://github.com/microsoft/CCF/blob/adc5d809768527e8e7ac772c41cf88e028a682fe/python/ccf/ledger.py#L187-L193

**Comment by achamayou** [comment]
This was correct when it was written, before read version tracking was added to enable BFT concurrent re-execution.

Arguably, the fact that this is enabled in CFT mode is a bug, since it is useless there and a pure performance cost. @ashamis could you have a look at what it would take to fix this?

As far as the doc goes, I would suggest changing the wording to something like "Read keys are only included in entry when running with BFT consensus" @letmaik.

**Comment by ashamis** [comment]
This was put into CFT mode to ensure that the BFT & CFT ledger formats matched, we can always go back on this.

**Comment by achamayou** [comment]
It's good to have the formats match, I completely support that, I'm just not sure it's useful to fill and serialise the contents?

**Comment by eddyashton** [comment]
The comments elsewhere are correct - we are _not_ actually populating the `reads` in the the serialised ledger in CFT mode, as the assert in `ledger.py` makes clear. I'd argue that the docs are accurate - they describe the format of the ledger so that tools can read it, but they don't talk about the transformation of an executed transaction to its ledger entry. We don't order writes or removes, we don't list intermediate writes. If we don't need to announce those transformations, do we need to announce that we don't store the read set (and explain further than the read set placeholder is only present so we can retain this format in future, if we ever need the reads for BFT variants)?

I'll tweak the docs page to try and make this clear.
