### ISSUE TITLE
`ccfciteam/ccf-app-run` Docker images don't contain CCF

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#2808]
```
$ docker run ccfciteam/ccf-app-run:0.19.3 ls -al /opt
total 16
drwxr-xr-x 1 root root 4096 Mar 22 15:08 .
drwxr-xr-x 1 root root 4096 Jul 15 16:56 ..
drwxr-xr-x 2 root root 4096 Mar 22 15:08 oe_lvi
drwxr-xr-x 6 root root 4096 Mar 22 15:07 openenclave
$ docker run ccfciteam/ccf-app-run:2.0.0-dev2 ls -al /opt
total 16
drwxr-xr-x 1 root root 4096 Jul  7 15:36 .
drwxr-xr-x 1 root root 4096 Jul 15 16:57 ..
drwxr-xr-x 2 root root 4096 Jul  7 15:35 oe_lvi
drwxr-xr-x 6 root root 4096 Jul  7 15:35 openenclave
```

Whereas the `ccfciteam/ccf-app-ci` image contains CCF:
```
$ docker run ccfciteam/ccf-app-ci:2.0.0-dev2 ls -al /opt
total 20
drwxr-xr-x 1 root root 4096 Jul  7 15:33 .
drwxr-xr-x 1 root root 4096 Jul 15 16:58 ..
drwxr-xr-x 9 root root 4096 Jul  7 15:33 ccf
drwxr-xr-x 2 root root 4096 Jul  7 15:30 oe_lvi
drwxr-xr-x 6 root root 4096 Jul  7 15:30 openenclave
```

**Comment by achamayou** [comment]
@letmaik that isn't a bug, it's by design, as per https://microsoft.github.io/CCF/main/operations/run_setup.html#runtime-container

The run image contains `cchost` and its runtime dependencies, which is all that's needed to run a CCF enclave image (either mounted, or present in a layer above in an image based on app-run). Because it's designed for deployment, it's very deliberately kept as small as possible.

Users who want the full SDK, for build purposes, are expected to use `ccfciteam/ccf-app-ci` instead: https://microsoft.github.io/CCF/main/build_apps/build_setup.html#build-container

**Comment by letmaik** [comment]
So, where do I find `cchost` in the image?

**Comment by achamayou** [comment]
It's in the $PATH:

```
$ sudo docker run -it ccfciteam/ccf-app-run:1.0.7
root@f76137e8e43f:/# which cchost
/usr/bin/cchost
```

**Comment by letmaik** [comment]
OK, I don't think it's obvious without any examples since the CCF debian package would install to `/opt` and since that package one isn't named `ccf-dev` or similar it creates the impression that this is the production thing you need to install, but `ccf-app-run` contains just the single `cchost` file from that package which is put into a different folder.

**Comment by achamayou** [comment]
We have looked at and discussed before splitting ccf into ccf and ccf-dev packages, which is indeed the debian convention. Two things have stopped us so far:

1. cmake/cpack didn't seem to support that particularly well.
2. current users have told us that they much prefer base images with in-sync Intel/Azure dependencies in-sync to debian packages.

If there's movement on either, we will reconsider.
