### ISSUE TITLE
Add optional `--defunct-network-cert` option to `cchost` for recovery

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3082]
As discussed with @msftsettiy, @sidmore and @lynshi

When recovering a service (i.e. ledger + snapshots), it would be nice to let operators specify the certificate of the defunct network certificate (new optional `--defunct-network-cert` option to `cchost`). Assuming that the ledger/snapshots and defunct service certificate are retrievable from different locations, this would mostly be about avoiding confusion when managing multiple ledger instances, by making sure that the operators have confidence that the service they're recovering is the correct instance. 

In particular, this would be useful to verify the endorsement of the recovery snapshot receipt early on, or verify that the service certificate matches the one recorded in the [`public:ccf.gov.service.info`](https://microsoft.github.io/CCF/main/audit/builtin_maps.html#service-info) table.

The option should be optional in case it is not possible for operators to retrieve the defunct service certificate before initiating the recovery procedure.

**Comment by achamayou** [comment]
s/node/network/ presumably?

The main element of confidence should not be expressed at node startup, where it is neither auditable nor secure, rather it should be done as part of the transition to open governance action, which is signed by the operator and therefore resistant to tampering from the host, as well as stored in the ledger and therefore auditable. It also precisely binds the new identity to the old, rather than allow any number of recoveries from one identity.

So while it is fine to add this as a convenience, it is no substitute for sending a precise transition to open proposal/vote.

**Comment by achamayou** [comment]
Implemented in #3624, but the documentation needs updating:

- [ ] https://microsoft.github.io/CCF/main/governance/open_network.html#opening-the-network
- [ ] https://microsoft.github.io/CCF/main/governance/proposals.html#creating-a-proposal
- [ ] https://microsoft.github.io/CCF/main/governance/accept_recovery.html
- [ ] https://microsoft.github.io/CCF/main/operations/configuration.html
- [ ] https://github.com/microsoft/CCF/blob/main/samples/config/recover_config.json
