### ISSUE TITLE
Serialisation of committed transactions is unsafe

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#338]
At it stands, when `serialise()` is called when a transaction is committed (`tx.commit()`), we assume that the serialisation cannot fail (or if it does, we throw a specific error that should be caught by the caller (i.e. `frontend.h`) to abort the processing of transactions immediately. 

Instead, we should recover safely, e.g. rolling back the store to the before the transaction was committed and returning a specific error message.

**Comment by eddyashton** [comment]
Updating with some further discussion from today:
- A common case of this that we need to handle is when serialisation fails because the write set is too large. We can write a unit test to easily repro this, writing a custom type with a custom serialisation function trying to write huge quantities of data.
- Rolling back is hard once we've generated a new commit index. Alternatives are to kill the executing node with an 'abort', or to commit some special tombstone marker to the ledger while returning an error to the user.
