### ISSUE TITLE
CCF 1.0.16. node_modules/@microsoft/ccf-app/crypto"' has no exported member 'SigningAlgorithm'

### ISSUE THREAD

**Issue by DavidZhongSyd** [microsoft/CCF#3415]
**Describe the bug**
I followed the instruction from https://microsoft.github.io/CCF/main/build_apps/js_app_ts.html to download the source code and run "npm run build". However, it popped up a series of error below.

I checked the crypto.d.ts crypto.js are under node_modules/@microsoft/ccf-app. But SigningAlgorithm does not exist in any crypto.d.ts crypto.js files. However, the SigningAlgorithm property is used in src/endpoints/crypto.ts: (102:24)

```
root@bc8570b00f15:/home/ccf-example-app/CCF/tests/npm-app# npm run build

> @ build /home/ccf-example-app/CCF/tests/npm-app
> del-cli -f dist/ && rollup --config && cp app.json dist/ && node build_bundle.js dist/


src/endpoints/all.ts → dist/src...
(!) Plugin typescript: @rollup/plugin-typescript TS2694: Namespace '"/home/ccf-example-app/CCF/tests/npm-app/node_modules/@microsoft/ccf-app/crypto"' has no exported member 'SigningAlgorithm'.
src/endpoints/crypto.ts: (102:24)

102   algorithm: ccfcrypto.SigningAlgorithm;
                           ~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'verifySignature' does not exist on type 'typeof import("/home/ccf-example-app/CCF/tests/npm-app/node_modules/@microsoft/ccf-app/crypto")'.
src/endpoints/crypto.ts: (112:28)

112   const result = ccfcrypto.verifySignature(
...
```

**To Reproduce**
git clone https://github.com/microsoft/CCF.git
cd CCF/tests/npm-app/

change package.json
"@microsoft/ccf-app": "^1.0.16",

run 
"npm install"
"npm run build"

**Expected behavior**
The app bundle can now be found in the dist/ folder and is ready to be deployed.

**Environment information**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Additional context**

**Comment by eddyashton** [comment]
Hi @DavidZhongSyd.

This is caused by a version mismatch; running the current version of the sample app from `main`, which includes references to `ccfcrypto.SigningAlgorithm`, with a 1.x release of the NPM `@microsoft/ccf-app` package. `SigningAlgorithm` was added after 1.0 and has not been backported to the 1.x branch, so is not present in any 1.x release.

To resolve this, either use a `file:` path to install the dev version of the package, or run the compatible `1.0.16` version of the app from [here](https://github.com/microsoft/CCF/tree/ccf-1.0.16/tests/npm-app).

That's our fault, as the docs are unclear - linking to the `main` version of the app but always recommending installing a released version of the package. Sorry for the confusion - we'll clarify the wording and links in the docs to make this distinction clear.

**Comment by eddyashton** [comment]
Thanks for raising this. We've now updated the docs to clarify this, and so that links to the GitHub repo from non-`main` versions links to the appropriately versioned source tree.

**Comment by jumaffre** [comment]
Just to add to what @eddyashton said, this will be true for all releases going forward (from 1.0.17 onwards) but we haven't backported this change to previous releases (because this would require patching the existing documentation on the fly, which is rather expensive/prone to errors). For example: https://microsoft.github.io/CCF/ccf-1.0.17/build_apps/js_app_bundle.html:

![image](https://user-images.githubusercontent.com/42961061/150107905-588c179b-b6dd-449d-a40b-9a7a21cd4d50.png)

**Comment by DavidZhongSyd** [comment]
Thanks @eddyashton and @jumaffre 

After I replaced all the files under npm-app with https://github.com/microsoft/CCF/tree/ccf-1.0.16/tests/npm-app, the "npm run build" is successful except one minor warning. Thanks for your help.

```
root@bc8570b00f15:/home/ccf-example-app/CCF/tests/npm-app# npm run build

> @ build /home/ccf-example-app/CCF/tests/npm-app
> del-cli -f dist/ && rollup --config && cp app.json dist/


src/endpoints/all.ts → dist/src...
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules/protobufjs/dist/protobuf.js
878: function inquire(moduleName) {
879:     try {
880:         var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
                       ^
881:         if (mod && (mod.length || Object.keys(mod).length))
882:             return mod;
created dist/src in 6.4s

```
