### ISSUE TITLE
Improve CCF release packaging

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3437]
We should improve the packaging of CCF releases to cater for different variants of CCF, i.e. sgx/virtual, development/production, C++/JS apps.

More details to follow.

This is very much post 2.0.

**Comment by achamayou** [comment]
I think it's useful to detail specific goals, for this and for any other ticket:

- We want users to easily find the right image for the task they want to perform "run a JS app", "build a C++ app", "test a change to CCF itself" etc.
- Performing each task should be efficient, ie. shouldn't require installing/downloading much more than is necessary
- Images and packages must be tested in order to work reliably. The accidental removal of a dependency (eg. curl) should be caught before it affects a user.

**Comment by achamayou** [comment]
We think the current image scheme is good enough.
