### ISSUE TITLE
When the last transaction is incomplete, it should be gracefully ignored by recovery

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3459]
If a ledger ends on an incompletely-written transaction, a node starting in recovery mode should ignore it like it does unsigned suffixes, and log a warning message.

There should be an end to end test checking that this is handled gracefully by dropping some number of bytes off the end of a ledger before attempting a recovery.

**Comment by jumaffre** [comment]
I've just tested this with the current `main` and recent changes in `host/ledger.h` have changed the behaviour of a recovery nodes around corrupted files:
```bash
# Starting a node in recovery mode with an incomplete ledger chunk "ledger_1`

2022-01-27T09:26:52.451676Z        100 [info ] ../src/host/ledger.h:765             | Renamed invalid ledger file "ledger_1" to "ledger_1.corrupted" (file will be ignored)
```

The current behaviour is too aggressive and we should instead let the enclave recover this file until it sees the corrupted entry, rather than marking the entire file as `.corrupted`.
