### ISSUE TITLE
ccf-app-ci:0.15.1 - new node cannot join the primary node

### ISSUE THREAD

**Issue by DavidZhongSyd** [microsoft/CCF#3470]
**Describe the bug**

I have legacy ccf code `FROM ccfciteam/ccf-app-ci:0.15.1` . (I know this version is no longer supported. I am currently doing the version upgrade)

The code passed all the integration test cases in 14 December 2021. However, in January 2022, I found the non-primary node cannot communicate to the primary node. In dev environment, it causes the node join from snapshot test case failed (not even in pending status). There is no code change during the period. Just feel a bit weird what is happening. 

May I ask if there some action made by CCF team to terminate some of the service running on ccf-app-ci:0.15.1 which cause the communication barrier between nodes? Thanks. 

**To Reproduce**

**Expected behavior**

**Environment information**
ccfciteam/ccf-app-ci:0.15.1

**Additional context**

**Comment by achamayou** [comment]
Hi @DavidZhongSyd, no specific action was taken, but the network certificate and certificates created by nodes with that release expired at the beginning of the year. Please see https://github.com/microsoft/CCF/issues/3352#issuecomment-1005484667 for more detail.

**Comment by DavidZhongSyd** [comment]
Thanks @achamayou

**Comment by DavidZhongSyd** [comment]
Thanks @achamayou .

Is there any way to update the network certificate or extend the network certificate expiration date? Thanks

**Comment by DavidZhongSyd** [comment]
In https://github.com/microsoft/CCF/issues/3352, you suggest to upgrade to 1.0.15. Will the code that is currently using 0.15.1 be compatible to 1.0.15. 

May I ask for the instruction to do the upgrade to 1.0.15 please? Thanks.

**Comment by achamayou** [comment]
Hi @DavidZhongSyd, our compatibility policy is outlined under https://microsoft.github.io/CCF/main/build_apps/release_policy.html, 1.x is not compatible with pre-1.x.

There aren't specific instructions for upgrade to 1.0, but looking at the C++ sample should give you an idea of what has changed: https://microsoft.github.io/CCF/main/build_apps/logging_cpp.html. You may find the release notes for releases from 0.15.1 to for 1.0 useful, in particular 0.99.0 (https://github.com/microsoft/CCF/releases/tag/ccf-0.99.0), if you hit any problems please do feel free to open a discussion and we'll try to help (https://github.com/microsoft/CCF/discussions).

**Comment by DavidZhongSyd** [comment]
Thanks @achamayou 
Right now in production, we only have one node in the ccf network due to this certificate expiration issue. Is there any quick fix to address this problem to have the rest node join the ccf network?

**Comment by achamayou** [comment]
@DavidZhongSyd if you want to avoid a recovery, I suppose you could try patching the release you are using to ignore expiry checks on join, but that's probably going to be fairly involved because that check will be in mbedtls, which is shipped by Open Enclave (one of CCF's dependencies), so it will involve a fair amount of re-building and patching.

If you go the recovery route, you can just target a new build where you have manually adjusted the validity of the network cert (see the first reply for a link to the place in the code). You will want to build the period-correct Sphinx documentation (./livehtml.sh), because the governance change quite drastically prior to 1.0 and the migration to JavaScript, so the current doc will not be very helpful.

Note that either way, pre-1.0 ledgers are not compatible with 1.0, so you will need to close the ledger you ran on 0.15.1 and start a fresh service on 1.0, and handle migration at the application level if necessary.
