### ISSUE TITLE
Add /gov/members

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3615]
Add a `/gov/members` endpoint that exposes a map of member ids to member info, including cert, status and additional data where applicable.

This is to make it easier for members to stage a recovery, particular when the status of recent key rotation is uncertain.

**Comment by lynshi** [comment]
Should this to be `/node/members` instead? This is public information anyway, and it makes it easier to connect to the endpoint. For example, if we have a client trying to figure out which member key version to use, if they pick the wrong version they won't be able to authenticate to `/gov`.

**Comment by achamayou** [comment]
@lynshi auth is independent of the frontend, we can make this un-authed on `/gov`, and that would be my preference because it's not really a node concern. We also open `/node` very early, when there's potentially no KV state and that query cannot be answered successfully then.

Regardless of where it goes, it is required that the endpoint be accessible on a 'recover' node, after the public ledger has been read completely, but before any other action is taken. Is that right?

**Comment by lynshi** [comment]
Sorry, I forgot we had changed that. Yeah, if `/gov/members` is un-authed then it works for us.

I think that sounds like a good point in time for the API to be available. Is that any different from the other endpoints - I'm not sure this needs to be available earlier relative to other `/gov` endpoints, because we don't need the results until we're about to submit a proposal anyway.
