### ISSUE TITLE
Support boolean query parameters in `http::get_query_value()`

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3674]
**Is your feature request related to a problem? Please describe.**
I'm using `http::get_query_value()` for strings and integers and would like to use it for booleans as well.

**Describe the solution you'd like**
While there are multiple possibilities, `true`/`false` as string values seem sensible and those are also defined in https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#http-query-parameters-and-header-values.

**Describe alternatives you've considered**
I've written my own code for booleans which is around 10 lines.

**Comment by achamayou** [comment]
@letmaik can you share your code? Do you expect "true" -> true and "false" -> false, case-sensitive, etc?

I think the difficulty here is that boolean support is less well-defined than string or integer ("true", "TRUE", "1", "yes" etc), and the framework tries to not to be opinionated about this sort of thing.

**Comment by letmaik** [comment]
The code I have is not generic, it simply uses `find()` on the parsed query and then matches against "true"/"false". I agree that's not the only option, and to support different values there would have to be a different API to provide the yes/no values. Feel free to close this if it's out of scope.

**Comment by achamayou** [comment]
@letmaik I have difficulty envisioning an API that would be much simpler than using the conversion to string, and a subsequent lookup in a user defined map<string, T>. You could pass the map to the API directly, but it's just having the API do `.find()` for you, and it only saves one line.

I think this is out of scope, because the benefit appears marginal now, and http::get_query_value() will disappear post-BL separation.
