### ISSUE TITLE
Publish unsafe variant as Docker image

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#3697]
There's already a Debian package. It would be convenient to have a Docker image with the unsafe variant as well.

**Comment by letmaik** [comment]
Can you give more details on what would be required in terms of effort? That would help potential contributors if there's more interest in this over time.

**Comment by achamayou** [comment]
@letmaik the dockerfiles need to either be templatised further, or made robust against new version names, and the GH Actions workflow needs to be adjusted. The plan is to move to MCR soon, so this will almost certainly have changed before anyone takes a look.

In general though, we are planning to keep the number of release artifacts to a minimum. Once we are on a platform with a more flexible attestation, we will almost certainly reconsider having separate builds in favour of making logging configurable at startup instead. The existence of the unsafe builds should be seen as a temporary workaround rather than a permanent arrangement.
