### ISSUE TITLE
Leader election must wait for quorum in each active config, rather than across all active nodes

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3948]
Follow up to https://github.com/microsoft/CCF/issues/3837

The current logic in CCF incorrectly uses a quorum across all active nodes: https://github.com/microsoft/CCF/blob/main/src/consensus/aft/raft.h#L1980

This can lead to multiple primaries being elected in certain circumstances, and although only one of them would be able to make progress, the other could cause nodes with valid logs to truncate them, affecting persistence.

**Comment by heidihoward** [comment]
Just to elaborate further.  

**Problem** 

Today CCF handles [reconfiguration](https://microsoft.github.io/CCF/main/architecture/consensus/1tx-reconfig.html) as follows: 

The current leader adds a reconfiguration txn to the ledger. This txn (and subsequent ones) are sent to all servers in both the old and new configurations. Once the next signature txn has been replicated by the current leader to a majority in both the old and new configurations, then the reconfiguration txn is considered committed. The leader switches to the new configuration.  Once the followers learn that the reconfiguration txn is committed, they also switch to the new configuration. Nodes that are not included in the new configuration will enter the “retired” state. 

This is the happy path where the leader who proposes the reconfiguration txn also commits it. The tricky bit is what happens if there are leader elections during this time? There are two options: 
* If the leader did not add a signature txn after the reconfiguration txn then the reconfiguration txn will be discarded during an election. 
* If a follower becomes a candidate with a signed but uncommitted (aka committable) reconfiguration txn in its ledger, then it currently needs a **majority quorum across both the old and new configurations** to become a leader. 

The 2nd option is a problem as the new leader might not have all previously committed txns in its ledger as it might not have votes from a majority quorum in the old configuration (see example discussed in https://github.com/microsoft/CCF/issues/3837). There can also be multiple leaders with the same term (for the same reason). 

This is not a problem if only one server is added/removed and there is only one reconfiguration in-flight at a time. 

**Fix** 

The proposed fix is to switch from the current logic where a candidate requires votes from a **majority across the active configurations** to requiring votes from a **majority in each active configuration**. I believe that the same change also needs to be made to the CheckQuorum logic.
