### ISSUE TITLE
Pending joining node should auto-create its own trust node proposal 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#397]
Further to https://github.com/microsoft/CCF/pull/395, the joining node should auto-create its own proposal so that it is convenient for members to trust the node without having to create their own proposals.

**Comment by olgavrou** [comment]
I was wondering how we want to behave if a node is explicitly voted to not be trusted?

Right now the node knows that it has been `trusted` if it gets the network secrets. How does it know to distinguish between being rejected and stop requesting to join vs just not being voted in _yet_, without any external communication? Also afaik if the vote to accept the node fails it just stays in state `pending` in the kv and we might want to change it to `retired` or add a `rejected` state or something similar.

**Comment by achamayou** [comment]
@olga the first change we need to make and which we’ve discussed last week is that there needs to be a way for votes to be rejected. Then the join rpc needs to expose this new state, and the rest is quite trivial.

**Comment by achamayou** [comment]
This is a slightly awkward use case, because it's sandwiched between the easy situation, where the Python test infra takes care of it, and the full blown deployment situation, where the orchestration code does it.

If it wasn't for the fact that we need to add a relatively far reaching exception to governance (and therefore audit), it'd be a tempting easy win, but as it is, I don't think we want to address it in the foreseeable future.
