### ISSUE TITLE
Misleading authentication errors when multiple auth methods are allowed

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#4044]
**Describe the bug**
If a CCF endpoint is configured with multiple authentication options, a misleading error may be returned if the user fails authentication. Specifically, if the user intended to use Auth Method A on an endpoint that has methods A and B (in that order), when A fails, the user may get an error message indicating that Auth Method B failed, which is misleading because it wasn't intended to be used.

**To Reproduce**
Configure a JS app with the following auth policies on an endpoint.
```
"authn_policies": [
  "user_cert",
  "jwt"
],
```

Attempt to connect to the endpoint with an invalid or unexpected user certificate. The returned error is

```json
{
  "error": {
    "code": "InvalidAuthenticationInfo",
    "message": "Missing authorization header"
  }
}
```

**Expected behavior**
While the reported error is technically true, an error for the intended auth policy would be more illuminating for the user. If it's not possible to detect the intended policy, an error message containing errors from all the configured auth policies would be helpful as well.

**Environment information**
CCF 2.0.4

**Additional context**
Reported by @caleteeter

**Comment by achamayou** [comment]
Establishing intent seems difficult in many cases. In a situation when both a JWT and a user_cert are present, what is the user intent if the endpoint allows either? If the header is missing, does that establish user intent to use user_cert? If not, is reporting an error about user_cert misleading (if the client just forgot to set the header but meant to)?

I think we want to look at reporting all errors if possible. I'm not sure how that fits in OData though.

**Comment by caleteeter** [comment]
@achamayou the ordering is significant here, but what seems missing is that if a method is missing content or incorrect content.  For example if the ordering is user_cert then jwt, if the user_cert is missing, then try the jwt, however if the user_cert is provided but is invalid then it should stop no?  I was going to check if the metrics would show the failures, possibly that is an alternative for users that experience these issues. 

It's a bit misleading to say the cert failed, then the jwt failed so we only tell the JWT failure (since it was last in order).

**Comment by eddyashton** [comment]
I'm wary of adding more complex rules for which auth policy failure is reported, because there's always going to be a few inconsistencies. A missing cert looks like the user wasn't intending to use cert-auth in this case, where we can fall-through to JWT auth, but when user-cert the only auth policy then a missing cert is a reported failure. With JWT auth, if we assume any request with an `Authorization` header is intended for this policy, we're potentially blocking later policies which want to use the same header, and also failing to report useful errors if a typo'd `Authsation` header is supplied.

We could concatenate error messages from all of the auth policies, but then we move further from standards compliance (ie - we can concatenate in the response body, but we also currently set `www-authenticate` indicating an invalid token; we can't concatenate the latter and have to favour a single policy).

Other possible solutions:
- Put the 'preferred' policy last. If the expectation is that 99% of users use cert auth, then put it last so they get useful errors. This still leaves misleading errors when JWT auth is intended.
- Define multiple endpoints, so user's auth intent is explicit in the URL path.
- Define a custom auth policy which supports multiple potential approaches, but where the application decides how to interpret intent/construct errors. This is possible but awkward in C++, and not currently extendable in JS.

None of these are really satisfactory, so I'll keep thinking about it. At the moment it looks like some kind of intent-capture rules in the policies is the approach we'll take, but we'll need to accompany that with documentation of exactly what each policy is looking for/will capture.

**Comment by achamayou** [comment]
@caleteeter the methods don't current make the distinction between missing and incorrect, and although they're specified as a sequence, the evaluation is a logical OR (https://microsoft.github.io/CCF/main/build_apps/auth/index.html), there is no sense of priority.

The metrics will register auth errors among others (errors are anything 4xx), but not separately from other errors.

**Comment by achamayou** [comment]
@eddyashton @caleteeter at least from a message format perspective, populating "details" with every failure seems quite straightforward: http://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#_Toc38457792
