### ISSUE TITLE
Verify SEV-SNP attestation security policy

### ISSUE THREAD

**Issue by DomAyre** [microsoft/CCF#4188]
Currently, we take the "measurement" from the SEV SNP attestation report and treat it identically to MRENCLAVE from SGX. This does some verification but isn't sufficient for full confidence.

Measurement is a digest of the UVM given to SEV SNP, host_data is a hash of the security policy applied within that container which verifies the code being run.

We should verify the policy at least matches a known good policy, this can be done in several ways:

- We have a new table in the KV which stores the unhashed policy, when a new node joins, we check the hash of the policy matches the hash on one of our known good policies.
- We verify the policy first, then hash it and treat the hash as a code_id

The former is likely better since when we eventually want to check for equivalence between non-identical policies we may need the unhashed good policy to do so.

**Comment by jumaffre** [comment]
Retrieving the security policy from the CCF node can be done via the `SECURITY_POLICY` environment variable, that's only available to pid `1` in the ACI container. This should be fine for a real deployment where `cchost` is the command specified as `command` in the container deployment (to be tested). However, for the CI, we currently do not pass any environment variable to the CCF node (so we'd have to explicitly pass this in) and we could for now hardcode the well-known `"allow_all:true"` (`eyJhbGxvd19hbGwiOnRydWUsImNvbnRhaW5lcnMiOnsibGVuZ3RoIjowLCJlbGVtZW50cyI6bnVsbH19`) security policy in the Python infra and use that.

**Comment by achamayou** [comment]
@jumaffre we could also default to fetching the starting node's container, grab its security policy digest, and default to that while leaving the actual policy contents blank.

We can log the fact that it's not set, and suggest setting the (otherwise undiscoverable) environment variable.

I'd rather not have too much test code/sandbox that sets allow_all, because we run the risk that it will be copy-pasted in a real deployments. Defaulting to the actual security policy of the first container seems safer in that respect, at the expense of a small amount of usability for a potential auditor.

**Comment by jumaffre** [comment]
@achamayou @DomAyre and I also talked about this but it'd be nice that a node always checks that, when writing a new key to the security policy table, the key is equal to the hash of the value.

This is very much a CI/dev environment only issue. We could also have the `command` dumps the value of the `SECURITY_POLICY` in a file that can then be read by the Python infra and passed on to each node as an envvar at startup, just like for a real deployment.

**Comment by achamayou** [comment]
@achamayou I'm not sure I understand, I think that requires that the user passes a security policy in manually. I don't think we want that, I think we want to either extract it automatically where available, or if it's missing, assume that it's whatever is applicable on the first container (same as mrEnclave).

**Comment by jumaffre** [comment]
@achamayou In the context of the CI, first container != first node. The SEV-SNP containers we use in the CI start an infinite loop as their `command` (pid `1`) so that we can connect to the container and run the CI agent. Each node then starts as a subprocess in this container, and even the first node in the service has a pid > `1` and thus cannot easily access the `SECURITY_POLICY` envvar, unless we pass it to it explicitly from the Python infra.

**Comment by achamayou** [comment]
Summary of offline discussion:

1. On startup, we attempt to capture SECURITY_POLICY, but if it's not there, we can still set security_policy_digest as an allowed entry, by fetching it from the attestation
2. if SECURITY_POLICY is set, we write as a value too, AND we check that its digest checks the security_policy_digest we get from the attestation
3. we can provide a sample transition_to_service_open variant that also performs the check in 2., and refuses to open the service otherwise, for users who want to ensure maximum auditability
