### ISSUE TITLE
Open ranges on the untyped map

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4238]
**Is your feature request related to a problem? Please describe.**

There isn't an easy way to perform open range queries that can get all items less than a key or all items greater than or equal to a key with the current range interface:

https://github.com/microsoft/CCF/blob/d34518da64e0012796b855fa8443189495d18c28/include/ccf/kv/untyped_map_handle.h#L69-L71

**Describe the solution you'd like**

A way to make either end open, with both being open meaning return every item.

Maybe:

```cpp
void range(
    const ElementVisitor& fn, 
    const KeyType& from, 
    const std::optional<std::reference_wrapper<KeyType>> to);
```

The `from` parameter should be open when the keytype is empty (e.g. an empty vector) but the `to` parameter needs an explicit option to specify its openness.

**Describe alternatives you've considered**

Making a big key and using that as the upper bound but it could always miss cases.

**Additional context**

https://github.com/microsoft/ccf-kvs/issues/23

**Comment by eddyashton** [comment]
Ideally we'd support this by exposing iterators over a KV map, rather than a foreach functor. Then we could use std algos like `std::upper_bound`/`std::lower_bound`, paired with `begin` and `end`, to iterate over these ranges.

For a quicker solution, I think we can wrap both the `from` and `to` types in `range()` with `optional`, with `std::nullopt` meaning an open range.
