### ISSUE TITLE
Ability to have a function called once the transaction is committed to modify the response

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4256]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to incorporate the transaction ID in the response since the commit only happens after we return.

**Describe the solution you'd like**

The ability to update the response with the transaction id, perhaps through another callback that gets registered.

Ideally this would not need to deserialise the response body again, instead using the existing one returned from the endpoint to avoid the extra overhead.

This could also tie in how the transaction id currently gets set as a header.

**Describe alternatives you've considered**

Guessing the transaction id which is unreliable.

**Comment by eddyashton** [comment]
Rough plan for this is split into 2 sections.

#### Adding dev-specified execution after commit
- Modify `ccf::endpoints::Endpoint` to contain a second function instance. As well as the current `func` (which is roughly `void (RpcContext, AuthnIdentity, Tx)`), we add something like a `locally_committed_func` (taking just `(TxID, RpcContext)`? Perhaps `AuthnIdentity` too, just in case, but definitely _not_ `Tx`).
- Move the [current post-commit behaviour](https://github.com/microsoft/CCF/blob/main/src/node/rpc/frontend.h#L467-L471) (which just sets the `TxID` into a header value) into a function, and use that for the default value of `locally_committed_func`. This should probably be invoked by the same pattern of normal execution, like we do on line 410 (`endpoints.execute_endpoint(endpoint, args)`) - call a virtual function on the `Endpoints` object, whose default implementation just casts to a concrete `Endpoint` and invokes the functor. This will make it easier to support the same behaviour in JS generic/other applications.
- Add a new method to `ccf::endpoints::EndpointRegistry`, like `make_endpoint_function_with_commit_handler(method, verb, func, locally_committed_func, auth_policies)`, which maybe does some type-fiddling and stores the new `locally_committed_func`.
- Add a sample instance/test case doing something more interesting (eg - inserting the `TxID` into the response body, rather than a header)
- Ensure that error-handling around this new functor is sound. This lets app-writers throw or do other dangerous things later than they previously could, and specifically later than the `Tx` is committed. If their new functor explodes, we should catch that and produce some standard error response including a description of the resulting `TxID`.

#### Persisting some response state between the functors
- The above can use the current `RpcContext`, and assume that the new functors either set a header, or deserialise the body, insert their own fields, and overwrite with the new serialised body (ie - they work with the existing `set_response_body(vec)`).
- To be nicer, and avoid these reserialisation costs, we can add a user data `void* response_user_data;` or similar in the `RpcContext`, with getter and setter.
- Rather than saying `response_body = serialise(my_real_grpc_response)` in the initial functor, handlers can now say `user_data = my_real_grpc_response`, and then in the post-commit functor say `my_real_grpc_response.append(tx_id); response_body = serialise(my_real_grpc_response)`.
- Need to make sure this user data is destroyed correctly, even if one of the functors throws and `RpcContext` is destroyed aggressively.
