### ISSUE TITLE
Tests have lots of missing method errors

### ISSUE THREAD

**Issue by jeffa5** [microsoft/CCF#4329]
**Describe the bug**

The e2e tests seem to be having lots of errors that might be being silently missed.

A CI run: https://dev.azure.com/MSRC-CCF/72f7306e-7f55-4927-84ff-ab872cf62cf5/_apis/build/builds/51076/logs/70 (search for 'Missing required methods'

**To Reproduce**

Locally:
1. Build ccf
2. From the `build` directory, run `ctest -R e2e_logging -V | tee test.out`
3. `grep 'Missing required methods' test.out` to see the missing ones.

**Expected behavior**

Either a loud failure at the end or a good explanation of why the test can be skipped. I would assume that these endpoints should exist.

**Environment information**

CCF main (afeee9bf0f626119bcbfa1555728e629266d37b4)

**Comment by achamayou** [comment]
@jeffa5 those aren't errors, the requirements decorators are a way to specify when some tests should be run. Typically, it's "when an application has certain endpoints". The reason there are so many of those is because we have a "suite" test that essentially randomly picks testcases, to fuzz a service instance. If that service is running an application package that does not support the endpoints, the corresponding tests may need to be skipped.
