### ISSUE TITLE
Point to TLA+ spec in documentation

### ISSUE THREAD

**Issue by lemmy** [microsoft/CCF#4484]
https://microsoft.github.io/CCF/main/architecture/raft_tla.html gradually becomes more and more outdated.  I suggest pointing to the actual TLA+ spec in raft_tla.html or sourcing it from the spec.

**Comment by achamayou** [comment]
@lemmy the spec snippets are extracted automatically, eg. https://github.com/microsoft/CCF/blame/main/doc/architecture/raft_tla.rst#L64

The paragraphs above each entry are manually maintained, but shouldn't have aged too badly? Does anything stand out in particular?

We can point straight at the spec, but we lose the TOC if we do that unfortunately.

**Comment by achamayou** [comment]
@lemmy we don't collect analytics, but I suspect you are effectively an overwhelming majority of our readers who are proficient in TLA+, so I'm very happy to make that change :)

We do lose two things that way (not that we exploited them very much in this case):

1. The ability to link from elsewhere in the doc to a specific section of the spec.
2. The ability to link to other bits of the doc (eg. C++ types), from inside the spec documentation.

This is of course due to the absence of TLA+ support in Sphinx, but it does make linking somewhat more tedious, we don't get the dead link checking etc.

The main improvement on `literalinclude` would come from adding pygments support, to get highlighting I think. Extraction of types and comments would be done through a domain I suspect, but would definitely be super nice.

**Comment by achamayou** [comment]
@lemmy I've folded what seemed to make sense in the spec. I've kept the intro and instructions in the doc, because I think they may be useful to newcomers.
