### ISSUE TITLE
`sandbox.sh`  defaults to 1 initial member instead of 3

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#4892]
By default, `sandbox.sh` sets up one initial member, but the docs specify an `--initial-member-count` of 3 (see below). 

https://github.com/microsoft/CCF/blob/b23beabf373ff0dfd4c74a94e222d74e47cc7af6/tests/infra/e2e_args.py#L236-L241

This ticket is low priority as three initial members can still be achieved by explicitly starting the sandbox with `--initial-member-count 3`.

**Comment by heidihoward** [comment]
I think this also impacts `--initial-recovery-member-count`

**Comment by achamayou** [comment]
The problem here is that e2e_args.py has defaults that are targeted at the end to end testing, where we typically want 3 members, which is a more realistic and interesting setting. For sandbox purposes however, a single member seems preferable, and makes recoveries easier for example.

When running the sandbox.sh with --help though, one gets the testing default, not the sandbox default.

I think a solution is to allow a env var override to some defaults, which the sandbox can set. This allows keeping context-dependent defaults, but with correct command line help.
