### ISSUE TITLE
Configurations not correctly updated on followers in TLA+ spec

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#4919]
@lemmy regarding that counterexample, `n4` should have removed `{n1, n2, n5}` from its configurations when it learnt that the next configuration `{n1, n4, n5}` had been committed. This should have been when `n4` updated its commit index to 2 or more. 

In general, when a reconfiguration transaction is committed, all configurations from earlier in the log should be removed from the configurations. The set of configuration is therefore the last committed reconfiguration plus any pending reconfigurations.

Aside, I believe that it is now the case that all terms start with a signature transaction.

_Originally posted by @heidihoward in https://github.com/microsoft/CCF/pull/4859#discussion_r1083873532_

**Comment by eddyashton** [comment]
> I believe that it is now the case that all terms start with a signature transaction.

@heidihoward This isn't actually guaranteed. When a node becomes primary it will emit a signature _soon_ after, but not atomically with becoming primary - it's possible for other writes to arrive and be applied first.

I think we decided this was still safe; if we consider each sequence of writes followed by a signature to be a single log entry in Raft terminology, then the first "entry" may be `[W1, W2, S]` rather than `[S]`, but the commit semantics of that entry are the same. The first transaction which may be _committed_ is still that signature (ie - the new primary will not advance commit to a signature from a previous term). Let me know if that's incorrect!

Another aside; I didn't think this would happen in practice as the window for these pre-signature writes is so small, but it does happen regularly in our e2e tests, as discussed in #4908.
