### ISSUE TITLE
How is the tps of CCF measured?

### ISSUE THREAD

**Issue by yingjun-wu** [microsoft/CCF#4929]
I know that it can be measured by means of continuous transactions, but the tps obtained by this method is relatively low, about 80 or so. How can I improve the measurement method to obtain a larger tps? 

Thank you!!

**Comment by eddyashton** [comment]
@yingjun-wu We measure and report the performance of every CCF build in this issue: https://github.com/microsoft/CCF/issues/1063

The client and deployment code producing those numbers is part of this repo, mostly submitted through [this client](https://github.com/microsoft/CCF/tree/main/src/clients/perf), and some through a [new system named Piccolo](https://github.com/microsoft/CCF/tree/main/tests/perf-system). We've also used some 3rd party performance testing tools, with the pros and cons of each summarised in [this comment](https://github.com/microsoft/CCF/discussions/2324#discussioncomment-3661060).

80 transactions per second is extremely slow, and far lower than the numbers we know CCF is capable of. I assume that is a single client submitting requests in series, and waiting for the response to each before submitting the next? In that case, the performance will be dominated by the round-trip latency between the client and the CCF node - the node is largely idle, and the transactions per second (throughput) is low as a result. If you're creating fresh connections each time this will be even worse, as the request roundtrip time will include multiple roundtrips to establish a TLS handshake. To obtain interesting throughput numbers with this kind of client, you'd need to spin up many of them in parallel, each independently submitting requests and aiming to saturate the CCF node/service. Our performance clients instead aim to saturate a node by _pipelining_ requests - multiple requests are submitted, without waiting for a response to the first. This allows a single, lightweight client to produce significant load on the service, saturating the throughput for some workloads.

Note also that as CCF is a general framework, the actual throughput observed will depend on the application code and the workload submitted. This is visible in our published performance results - some are testing simple writes, some do significant transformations and multiple writes, some execute in a JS interpreter rather than native code. If you can tell me more about your application code, and the workload you're testing, I may be able to advise further.

**Comment by yingjun-wu** [comment]
thank you for your reply! The scenario I tested is to send a new request asynchronously every time, i know it will be worse as you said above. How can I improve the measurement method in the way of asynchronous requests? @eddyashton

**Comment by achamayou** [comment]
@yingjun-wu could you clarify what you mean by asynchronous requests?

**Comment by achamayou** [comment]
Please re-open this issue if there is an update.
