### ISSUE TITLE
Compile failed on ubuntu 20.04 for main branch

### ISSUE THREAD

**Issue by wheatli** [microsoft/CCF#4984]
**Describe the bug**
Clone the main branch, build source in virtual mode, get the following error:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/23206367/217841610-ce8b9e77-c8d2-4951-b8b3-9f62a7bf7817.png">

**Comment by eddyashton** [comment]
Hi @wheatli. It looks like your build is using `clang-12`, but is unable to find the C++20 std lib `<span>` header. That may be due to a missing package or other misconfiguration of your build machine, but is hard to diagnose without more information.

CCF is primarily built and tested with `clang-10`, as described in the [documentation](https://github.com/microsoft/CCF/blob/main/src/clients/perf/scenario_perf_client.cpp). The simplest way to ensure all of the necessary tooling is correctly installed is to run one of the Ansible playbooks under `getting_started`, or to use one of the published release images. For app development, you should use a CCF release and should not need to build CCF itself from source.

**Comment by achamayou** [comment]
Please re-open if necessary.
