### ISSUE TITLE
GET /nodes/self returns 500 when the node is Pending

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5064]
This is because the KV doesn't contain the node info yet, but it's entirely known from the config and could be returned.

**Comment by lynshi** [comment]
Providing some context from the discussion.

We made a change to use the endpoint for fetching the node id (to be able to trust the node) thinking it was nicer than querying `/node/network/nodes` and matching by IP information. After some discussion with @achamayou, we concluded that it's better to fetch the info from the service to prevent a malicious node from reporting an incorrect node id (e.g. of another node that is pending). Of course, this is a difficult attack to pull off - all nodes involved must still be running attested code - but we'll switch back to using the service's information for more obvious safety.

We don't have a specific requested change, so either of the following could work:
1. Fix the behavior so info is returned when the node is pending, if this does not seem like an issue for safe, "correct" operation.
2. Return a more illuminating error message and/or add documentation for this issue so that customers aren't confused when hitting an endpoint that should reasonably be available.

**Comment by achamayou** [comment]
@lynshi the node info returned is entirely supplied by the node from its configuration. It could be served by the node pre-join without creating any safety or security issues. It's probably the right thing to do here.

**Comment by lynshi** [comment]
Right - I meant it was unsafe in the specific use-case we were discussing, which is getting the node id so that a proposal to trust the node can be submitted. Perhaps a reasonable thing to do is to leave it empty until trusted? Agree that the rest of the info is a non-issue.
