### ISSUE TITLE
Different listening addresses not sufficiently documented

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#516]
```
  --node-address REQUIRED     Node-to-node listening address
  --rpc-address REQUIRED      RPC over TLS listening address
  --public-rpc-address REQUIRED
                              Public RPC over TLS listening address
```
The docs don't have further information on these and I'm a bit confused what each of them should be, esp the difference between rpc and public rpc. Does it make sense to have sensible defaults here?

**Comment by achamayou** [comment]
Yes, the sensible default is for --public-rpc-address to default to --rpc-address.

The two are separate because nodes can and do advertise other endpoints to clients, and if the CCF nodes are NATed, the public IPs will differ from the IPs the nodes are listening on without any way for the nodes to automatically discover this. This clearly needs to be documented better.

**Comment by eddyashton** [comment]
Clarified in #518.
