### ISSUE TITLE
GET /node/network/nodes/self redirects may be inaccessible from the public Internet

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#5184]
**Describe the bug**
We've previously observed that `GET /node/network/nodes/self` redirects the client to an address containing the node's id. For example, `https://$nodeIp:$nodePort/node/network/nodes/$nodeId`.

If the node is running inside a private network, redirects to the private IP won't work for public connections. I'm not sure if `$nodeIp:$nodePort` comes from the `published_address` parameter in the node's configuration, but even if it does, the parameter may be meaningless publicly for networks that don't expose nodes individually.

We previously agreed the redirect itself is fine, though I didn't try out connections from public clients because that wasn't what I was testing. However, now that I've found this issue, there's probably two things that can be done:
1. Redirect to a URI containing the node's id, but the hostname should be the public host. Assuming `published_address` is intended to be different per node, this might require an additional configuration parameter like `service_address`. Alternatively, you can get the hostname used by the client (e.g. in the `Origin` header..?), and just use that for the redirect because it guarantees accessibility by the client.
2. Don't redirect at all and return the info directly.

**Environment information**
CCF 2.0.10 (though I think the behavior has not changed since)

**Comment by achamayou** [comment]
> I'm not sure if $nodeIp:$nodePort comes from the published_address parameter in the node's configuration

It is the published address: https://github.com/microsoft/CCF/blob/b0e95aeb5d104304096a1f753cd47a6d9f46d3bd/src/node/rpc/node_frontend.h#L1173

I am skeptical about option 1., because it seems to me that if `service_address` (or the client hostname) is a load balancer, there's a potential race condition where `/self` effectively gets sent to another node. In some cases, that could result in a 404 if that other node is behind. For example:

```
GET http://load-balancer/node/network/nodes/self [load-balancer -> node1]
308 Location http://load-balancer/node/network/nodes/node1

GET http://load-balancer/node/network/nodes/node1 [load-balancer -> node2]
404 No such node (node2 doesn't know about node1 yet)
```

This will probably go away eventually, as node2 catches up, but it's quite unnecessary.

Option 2. doesn't suffer from that edge case (except in #5604, but that's a separate problem). It's worth noting that `/{node_id}` is subtly different from the comparatively simple `/self` endpoint now: it potentially forwards to the primary if the session had been previously forwarded. This is to guarantee consistency, which in this case amounts to being able to read potential writes to the nodes table (eg. updating `node_data`) made previously on the session. `/self` doesn't need to do that, because it only resolves the node_id, which is immutable, and is set never to forward.

I don't think this changes the fact that Option 2. is more user-friendly, but I thought I'd still point it out.

**Comment by lynshi** [comment]
Just a note - presumably `/primary` exhibits the same behavior as `/self` (in terms of redirecting to a private IP).
