### ISSUE TITLE
Handling of initial configuration in TLA+ spec does not match implementation

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5220]
The reconfiguration-related raft_scenarios such as `tests/raft_scenarios/election_while_reconfiguration` initialize configurations[n] for some n \in Servers to equal {}.  If this is just an artifact of the raft_scenarios, we can work around it in thee trace validation spec.  If not, I suggest correcting `InitReconfigurationVars`:

https://github.com/microsoft/CCF/blob/64c2df38fa45f03be5dd90ea554e86b0ba5b8a3e/tla/ccfraft.tla#L361-L367

_Originally posted by @lemmy in https://github.com/microsoft/CCF/issues/5173#issuecomment-1512162552_

**Comment by heidihoward** [comment]
It is currently the case that the TLA+ spec does not handle the initial configuration in same way that the implementation does. 

The spec simply initializes all  `configurations` to include the initial configuration. There is no reconfiguration txn for the initial configuration.

My understanding (discussed with @achamayou this morning) is that the implement requires that the initial configuration has only one nodes. This node starts as a follower (with an empty configurations?), waits for the election timer and becomes candidate and then leader. The first transaction added (aka genesis transaction) is a reconfiguration transaction to set the current configuration to the initial configuration. This transaction is committed as usual only after a signature (which may not be the next transaction?). There is then another reconfiguration txn to move the single node configuration to the real initial configuration. The other nodes have empty configurations until they receive a successful append entries. I assume that there's no risk of the single node stepping down (either due to check quorum or higher term) and thus rolling back the genesis transaction is impossible.

**Comment by achamayou** [comment]
Sorry, there was a little confusion:

> the implement requires that the initial configuration has only one nodes.

It doesn't particularly require it, but that's how it's done. A node is run in `Start` mode, which creates a network (a one node config, and identity etc). Further nodes are started in `Join` mode and pointed to it. (There is a parallel scheme for `Recovery`).

> This node starts as a follower (with an empty configurations?), waits for the election timer and becomes candidate and then leader.

I was proposing that as a change, but the current behaviour is that the `Start` node just becomes primary:

https://github.com/microsoft/CCF/blob/61ec90c7e39ce26bddbdeb865551ccd34cf06e00/src/consensus/aft/raft.h#L328, called from https://github.com/microsoft/CCF/blob/61ec90c7e39ce26bddbdeb865551ccd34cf06e00/src/node/node_state.h#L541

> This transaction is committed as usual only after a signature (which may not be the next transaction?).

Yes. I think in practice it is the next signature, because the frontends aren't opened yet and the node isn't emitting anything else. But it's somewhat coincidental rather than strictly guaranteed or enforced.

> There is then another reconfiguration txn to move the single node configuration to the real initial configuration. 

Raft gets notified of the reconfig by the KV hook, triggered by the (re)configuration transaction.

> The other nodes have empty configurations until they receive a successful append entries. I assume that there's no risk of the single node stepping down (either due to check quorum or higher term) and thus rolling back the genesis transaction is impossible.

Yes, and yes.

A good way to check this is to generate a trace from a node (build and run one of the end to end tests with `-DCCF_RAFT_TRACING`), or inspect its ledger with `read_ledger.py`.

**Comment by achamayou** [comment]
Resolved by #5828, and later PRs that ported scenarios over: #5906 #5907 #5909 #5910 #5911 #5912 #5915 #5918 #5929.
