### ISSUE TITLE
Document CPU usage behaviour

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#527]
`cchost` uses two of my cores fully, which displays as 200% cpu in `top`. That is unexpected and should at least be documented. I'm assuming it does some kind of busy wait inside the enclave. Does that mean two cores are always blocked by ccf and cannot be used for other applications on the host?

**Comment by achamayou** [comment]
Yes, the ring buffer readers on either side of the enclave boundary are currently busy spinning. It does not mean that cores are blocked by CCF, unless you select a non-preempting scheduler. We will document this (and also probably change it to some extent, so that after a number of idle loops, we ocall out to sleep or something similar).
