### ISSUE TITLE
Logs during startup with --config-timeout

### ISSUE THREAD

**Issue by lynshi** [microsoft/CCF#5438]
**Is your feature request related to a problem? Please describe.**
When `--config-timeout` is specified, `cchost` waits for the configuration file to be present before starting. However, while it is waiting, nothing is logged, so it is not obvious that it is running correctly. For someone unfamiliar with the behavior, they may think that something is wrong.

**Describe the solution you'd like**
While waiting for the configuration file, `cchost` should periodically log that it is waiting or that the configuration file is found but is invalid. It might be useful to further display some information about the time elapsed, total timeout, and interval at which `cchost` checks for a valid configuration.

**Comment by achamayou** [comment]
@lynshi this is awkward, because the logging isn't initialised when we are waiting for the config. And the reason it's not initialised is because we're waiting for the config to tell us how the logging [should be configured](https://microsoft.github.io/CCF/main/operations/configuration.html#logging)!

We could, conceivably, default to say, INFO and Text. But if you then configure JSON, you'll get a mixed log, and vice versa. Not a great user experience.
