### ISSUE TITLE
Error joining node to network with ACME endorsed certificate

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5515]
Hello, I am getting error when I try to join a node to network with ACME Endorsed certificate.
![image](https://github.com/microsoft/CCF/assets/65513238/05e7cf1f-85a4-4235-be6e-cf0af7c4b03f)

Join configuration looks like this:
IP addresses are anonymised

```
{
    "enclave": {
        "file": "/opt/ccf_sgx/lib/libjs_generic.enclave.so.signed",
        "type": "Release",
        "platform": "SGX"
    },
    "network": {
        "node_to_node_interface": {
            "bind_address": "...:6600",
            "published_address": "...:6600"
        },
        "rpc_interfaces": {
            "main_interface": {
                "bind_address": "...:443",
                "published_address": "...:6600"
            }
        }
    },
    "node_certificate": {
        "subject_name": "CN=CCF Node",
        "subject_alt_names": [
            "iPAddress:...",
            "dNSName:dnsname.com"
        ],
        "curve_id": "Secp384R1",
        "initial_validity_days": 1
    },
    "command": {
        "type": "Join",
        "service_certificate_file": "/home/azureuser/service_cert.pem",
        "join": {
            "retry_timeout": "1s",
            "target_rpc_address": "...:443"
        }
    }
}
```

**Comment by achamayou** [comment]
@kristupaslozoraitis the interface used to let new nodes join must be endorsed by the service identity, no other CA is acceptable. Otherwise the operator wouldn't know which service the node is joining.

You will need to configure at least one RPC interface with `"endorsement": "Service"` and use that for joining new nodes.

**Comment by kristupaslozoraitis** [comment]
@achamayou So this RPC interface with `"endorsement": "Service"` should be created in network `Start` config, not in `Join` right?

**Comment by achamayou** [comment]
@kristupaslozoraitis all nodes must have such an interface under `rpc_interfaces`, both Start and Join, since they may be called by a new node wishing to join the network later.

A quick scan through the documentation reveals that we do not make this requirement particularly clear, I will correct that.

**Comment by achamayou** [comment]
Note in principle that you could swap `"service_certificate_file": "/home/azureuser/service_cert.pem",` to point to the Let's Encrypt CA, and that you may be able to join that way.

This is not tested, supported nor encouraged though, since you wouldn't have any certainty about the network your node is joining other than it's endorsed by Let's Encrypt, which isn't very specific.

**Comment by kristupaslozoraitis** [comment]
The interface with "Service" endorsement helped with the problem. Thanks
