### ISSUE TITLE
Cannot use /usr/lib/x86_64-linux-gnu/libmbedtls.a

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#565]
**Describe the bug**
Installing host mbedtls via apt get will put it in `/usr/lib/x86_64-linux-gnu/libmbedtls.a` which you can't tell CCF's CMake to use as it assumes the library is in `<prefix>/lib/libmbedtls.a`.

**Expected behavior**
CCF's CMake scripts should use CMake functions to locate libraries etc, e.g. find_library. See https://github.com/curl/curl/blob/master/CMake/FindMbedTLS.cmake for inspiration.

**Environment information**
Mainly I'm not using the CCF Ansible scripts to prep the build machine/docker image.

**Comment by achamayou** [comment]
Thank you for the link to the inspiration :)

There are a couple of problems with that approach though:

1. Because it's path driven it does not come with very good garantees that you end up with a matching headers/library set
2. Because it's path driven, it's fairly awkward to switch between multiple different mbedtls installs

As it happens, both of those have been problems for us in the past, although not so much now. I am tempted to propose that we default to your approach, and switch back to ours if CLIENT_MBEDTLS_PREFIX is specified. What do you think?

**Comment by letmaik** [comment]
Yes, sounds ok. I think you worry too much though :p

**Comment by achamayou** [comment]
@letmaik we had serious problems with this in the past when OE would install its own mbedtls headers in the include path but the libraries under its own prefix.

We also used variants of mbedtls with various degrees of Everest integration, with similar problems :) These concerns aren’t purely theoretical ;)

I do agree that what you propose is a reasonable default however, and I will make the change!
