### ISSUE TITLE
ccf_cose_sign1 signing key and certificate

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5742]
Hello, I was trying to find a way passing `--signing-key` and `--signing-cert` as a plain text not reading from file but I didn't find.

I am interested why there is no such an opportunity to give those two files content as a text?

Besides, do you see this as improvement in future plans? Because when I have been implementing CCF I was thinking about possibility to not store members' keys in CCF but pass only when it is required. But at the moment there is no opportunity due to `ccf_cose_sign1` package to not let pass `--signing-key` and `--signing-cert` in other way than file. 
What's your thoughts about it?

**Comment by achamayou** [comment]
@kristupaslozoraitis if you call the Python package directly, you can pass those values as PEM strings directly, without going through a file: https://github.com/microsoft/CCF/blob/c2f42d4d08e6ca180ba1040382dd445e49b86812/python/ccf/cose.py#L111

The CLI does not support that, and most command line interfaces usually would not because they are not confidential, and so anyone on the machine who runs `ps` for example would be able to read your signing key, they also might get stored in your bash history, in logs etc.

Files have permissions and aren't subject to these issues. For that reason I don't think we will add the functionality, but I'm also happy to hear your perspective on this.

**Comment by kristupaslozoraitis** [comment]
Thank you for clarification!

**Comment by eddyashton** [comment]
> Because when I have been implementing CCF I was thinking about possibility to not store members' keys in CCF but pass only when it is required

The keys aren't stored in CCF itself, but if you mean they need to be available directly on the client, then we have documentation explaining how to avoid this:
https://microsoft.github.io/CCF/main/governance/hsm_keys.html#cose-signing

In short the `ccf_cose_sign1` CLI does signing, so needs access to the signing keys. If you want those keys to live elsewhere (eg, in a key vault), then you can separate the steps:
- `ccf_cose_sign1_prepare` produces a TBS (to-be-signed)
- That TBS is passed to the signing system, which closely manages access to the keys (only uses them for signing), and returns a raw signature
- That raw signature is packaged into a CCF request body with `ccf_cose_sign1_finish`
- The output of that final tool is submitted to the service, exactly the same as `ccf_cose_sign1`
