### ISSUE TITLE
Opportunities to tidy up `raft.h`

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#5894]
Whilst comparing `raft.h` to the TLA+, I spotted a few possible opportunities to tidy up `raft.h`. None of these changes should alter the behavior of `raft.h` (though I might be wrong!).

1) `new_view_idx` appears to be unused
2) unused if statement https://github.com/microsoft/CCF/blob/8f6d14c6f42264f30c5a65b5c745d6586317978b/src/consensus/aft/raft.h#L1109-L1118
3) Comment out-of-sync with code https://github.com/microsoft/CCF/blob/8f6d14c6f42264f30c5a65b5c745d6586317978b/src/consensus/aft/raft_types.h#L161-L168

**Comment by achamayou** [comment]
@heidihoward just to make sure, about item 2, the reason: https://github.com/microsoft/CCF/blob/main/src/consensus/aft/raft.h#L1187

is unused, is because it is redundant with:

https://github.com/microsoft/CCF/blob/main/src/consensus/aft/raft.h#L1149

checking a value produced by:

https://github.com/microsoft/CCF/blob/main/src/consensus/aft/raft.h#L1141

which includes the same check:

https://github.com/microsoft/CCF/blob/main/src/consensus/aft/raft.h#L957

right?

**Comment by achamayou** [comment]
Item 3 I believe has already been addressed by https://github.com/microsoft/CCF/commit/31ef76a0aed6cc81f96d0153fb75a5537ff7d045#diff-758d925fefddddd48aadb8f7b8879f341a4c67463719bc7f8aee51fdeedd62a6

Other items should be addressed by https://github.com/microsoft/CCF/pull/6174
