### ISSUE TITLE
ACME failed

### ISSUE THREAD

**Issue by kristupaslozoraitis** [microsoft/CCF#5898]
Hello, when I am starting a network I am getting an error regarding ACME 
![image](https://github.com/microsoft/CCF/assets/65513238/1e156b39-fa9e-4962-b54c-21ca964ef1b0)

I have 3 virtual machines, but 2 virtual machines starts network correctly and one is getting error. What is the reason that one environment is working correctly with the same network configuration and the other getting error which is in the screenshot above. Thank you

**Comment by achamayou** [comment]
@kristupaslozoraitis it would be useful if you could share more of the log. As it stands, it looks like Let's Encrypt has rejected the validation attempt ("invalid" is final), because it couldn't fetch the nonce at the expected location. That could be because the server isn't available at the expected location (incorrect DNS?), or because the serving of the nonce by CCF wasn't done properly (hard to tell without more logs).

**Comment by kristupaslozoraitis** [comment]
@achamayou DNS which was provided in the network configuration was not even registered. There was the problem. Thank you very much!
