### ISSUE TITLE
Quote freshness for join protocol

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#59]
See discussion below

**Comment by achamayou** [comment]
This is connected to #178. It isn't enough to do this for TLS, we must also include the service identity in quotes.

To do so, the quotes will need to be over the service cert and a TBS, "To be signed", which is the cert of the node, endorsed by the service, but unsigned.
This TBS will be emitted by the service, for the joining node, to ensure quote freshness. Quotes over stale TBSs will be rejected.

Additional investigation regarding the exact implementation of the TBS with mbedtls is necessary before this feature can be implemented.

**Comment by achamayou** [comment]
```
Cj: joiner cert
Cs: service cert
Cn: node cert, where node is part of the service

JOINER                            SERVICE
self-signed Cj ------- TLS -------> Cs Cn
            <--- TBS(Cj) ----------
            - quote(Cs, TBS(Cj)) -> [entry written to KV as PENDING]
                                    [VOTE]
                                    [ entry updated as TRUSTED, and identity as Cs Cj]
[ DONE ]    <--- secrets ----------
```

**Comment by achamayou** [comment]
An additional requirement, connected to #47, is that Cs should contain alpha, the relevant enclave initialisation parameters.

**Comment by jumaffre** [comment]
Splitting this issue. https://github.com/microsoft/CCF/issues/552 now deals with certificate endorsement while this ticket is about quote freshness.

**Comment by achamayou** [comment]
```
      // TODO(#important,#TR): The "alpha" parameters, including the unique
      // service identifier, should also be included in the quote.
```

**Comment by jumaffre** [comment]
Reviving this ticket after work and discussion about #2554 with @achamayou and @wintersteiger.

The solution described in previous comment is now outdated: it is no longer the node certificate that is quoted but the node's public key, since the latter is stable during the lifetime of the node but the certificate may be refreshed. 

The new solution should still address the following issue: a now-retired node got compromised and its identity (i.e. TLS) private key stolen. A new malicious node (e.g. running the modified virtual version of the enclave) uses the leaked private key to connect to the service and presents the public quote (available in the clear in the historical ledger) from the now-retired compromised node. With the current implementation, if the MRENCLAVE of the old node is still valid, the service would successfully accept the compromised node and, once the members have voted to trust the new node, leak the ledger secrets to the service. The attack isn't trivial and there are measures that operators/members can take to avoid this in the first place: remove compromised MRENCLAVEs, audit the node carefully when trusting it, etc. **Note that the freshness issue described here doesn't affect 1.x releases as we don't remove node identities from the store when they're retired and as such nodes identities cannot be re-used by other malicious nodes.**

To guarantee freshness, the first thought was to include a nonce (supplied by the existing primary) in the quoted data of the joiner. The nonce would be passed in a new first round-trip between the joiner and the primary and would have to be included by the joiner in the quoted data. This complicates the auditing story from clients slightly as they would have to be made aware of the nonce somehow (probably using a new custom extension in the node's x509 certificate), hash it, etc. However, using a nonce there only minimises the window during which the attack can take place: since the join protocol can take a long time and spawns multiple TLS sessions (so that it's robust to primary changes, etc.), it is possible that the node which completes the join protocol (and gets given the ledger secrets) isn't the same node which started it. **So as we currently understand it, the nonce solution isn't viable either.**

The team will discuss this further in the next few days and update this ticket accordingly.

**Comment by jumaffre** [comment]
As discussed today with @fournet, @ad-l, @achamayou and @wintersteiger, the preferred option is to verify that the time at which the quote was produced is recent "enough" at the time it is verified. The "enough" would typically be a time period defined by member governance, long-enough for the multi-step join protocol to complete successfully, but short-enough to avoid compromised nodes joining the service instead (e.g. 1 day?). 

The time extraction and verification should be done in two places: 1) on the first join, before recording the new node as `Pending` (*), 2) when the member proposal to transition a new node to trusted is executed. 

Note that this relies on the possibility to extract the creation time from a quote, which isn't offered by Open Enclave yet (see for example https://github.com/openenclave/openenclave/issues/4105).

This should also work with BFT, as long as all nodes have access to a loosely synchronised time.

(*) Join policies should be defined by member governance as flexible JS scripts. Feature pending.

**Comment by achamayou** [comment]
We'll re-open this when attestation capabilities improve.
