### ISSUE TITLE
Explore ETAGs support to provide session consistency

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#6081]
We believe it should be possible to provide a HTTP-standard form of session consistency by processing ETAG headers in CCF. This will need to be domain/app-specific, but we could prototype it within governance to confirm it is viable.

**Comment by achamayou** [comment]
Having thought about this some more, I am not sure the governance flow is ideal for this, because:

> The ETag (or entity tag) HTTP response header is an identifier for a specific version of a resource. [0]

But governance resources (in the HTTP sense of the word), proposals and ballots, are not mutable and only ever have a single version. Creation produces a new resource, and the outcome of a racing GET will not change if an ETag is specified. The same applies to ballots, when they are submitted. Re-submission is a failure unless the ballot is the same. Similarly, withdraw would not behave differently with ETags.

An argument could be made for capturing not just the proposal but proposal + existing ballots in an ETag, to support conditional submission ("submit this ballot on this proposal only if exactly these other ballots have been posted"). This seems a bit niche, but seems like the only conceivable use of ETags in governance.

Similarly, there is no obvious condition to be applied on ack/share refresh or submission. There is already a pre-condition check and failure if the value is not current.

A better sample would be the logging app I think, where the ETag could be the digest of the value or the version of last write, and where submission with If-Match would fail if the value has changed in the meantime.

[0] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by achamayou** [comment]
> the ETag could be the digest of the value or the version of last write

Using the version of last write precludes returning an ETag on log entry creation at the moment, unless using a local_commit_handler (C++ only), because the version is not set by the time the user handler completes.

The logging example in its current form is also not completely ideal because entries are not HTTP resources, and are instead POST'ed and queried.

**Comment by eddyashton** [comment]
We have a demo of this, and helpers in the public C++ API, in #6110.
