### ISSUE TITLE
In the KV API, it should be possible to have read-only TxViews

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#61]
Imported from an earlier code TODO, I cannot find context for this.

**Comment by achamayou** [comment]
@eddyashton how do we think this should work? From a pure KV perspective, it seems easy to specify that at construction, and to throw at the first put. It's not clear exactly what that buys us in the context of CCF though?

**Comment by eddyashton** [comment]
I think the goal was to get support from the type system. So if you declared a read-only handler, it would get a `ReadOnlyTx` rather than a `Tx`, and the produced view types wouldn't even have a `put` method? Its a small facet of "what should the kv API look like for apps".

**Comment by eddyashton** [comment]
From my memory, may not match current code: if you declare a handler as read-only but then `put` inside it, then the results are inconsistent. If you send it to the leader, it will be executed successfully. If it goes to a follower, it will produce an obscure error that the transaction could not be replicated. We could throw on 'put', after setting a flag at construction (maybe? Do we know if the eventual handler is read-only at Tx-construction?), but this still leaves the space of handlers that _sometimes_ call put (`if (rand() % 1000 == 0) { view->put(...); }`) - it would be nice to block all of these at compile time.

**Comment by achamayou** [comment]
`ReadOnlyTx` makes sense, although as you point out, it won't help MayWrite handlers. Until we dispatch on (path, verb), it's also awkward because the typical REST pattern will be to have read/write variants of the same resource, so it will only be usable in a few places which are GET/Read-only.

An added complication of throwing on put() is that even `Read` queries will in fact be doing some writes when used with PBFT, so the interface would need to be split between internal usage and user-facing code.

This is also not going to benefit dynamic runtimes. I think a realistic short-term goal would be to add tests & handling for the case where writes are aborted on a secondary to ensure we return a friendly and descriptive error to the client. What do you think of that reduction in scope? Does it make sense?

**Comment by eddyashton** [comment]
Its not just PBFT. If we get signed read-only requests, we still `put` to store the signature. I think this is another reason to look at some kind of sub-transaction model - the framework can see the full-fat `kv::Tx` while the application only gets a smaller, independently-revertible object.

For dynamic runtimes I agree - they could implement read-only restrictions themselves but they're presumably taking a more general writeable `Tx` object at the language boundary. There's space for other types of dynamic runtime apps (ie - where the C++ declares the endpoints/handles dispatch, but the actual handling logic is delegated to another runtime) where the type safety still means something, but I don't think they're a natural model.

In terms of scoping, I see this task as a small non-critical part of the need for a cleaner KV API. We don't _need_ to offer a read-only variant, but we _should_ expose a trimmed down object that apps can't call `commit` on, and can't create themselves. In the rewrites to support that it'd be nice to consider this, as well as sub-transactions (#1065, maybe higher priority) and `kv::Value`, `kv::Set` (#274).

I'm not sure about the aborted-writes-on-a-backup. It looks like actually have a test ("Signed read requests can be executed on backup") confirming the opposite behaviour. But this works because we validate-but-drop the signature for read-only transactions to backups: the signature-storage behaviour is inconsistent, and we can only get receipts if it goes to the leader. We can build a more precise error ("Replication failed: Raft write on backup - handler marked as read-only produced write(s)"), but I'm not sure of the value in this since it looks like we need to do at least some KV API changes anyway.

**Comment by achamayou** [comment]
The backup/primary difference when handling signed reads sounds like a bug, I can't imagine why we would do that deliberately.

**Comment by achamayou** [comment]
Solved by #1310
