### ISSUE TITLE
Allow HTTP endpoints to support arbitrary content-types

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#634]
HTTP endpoints should support arbitrary content types, not just JSON.

**Comment by eddyashton** [comment]
There's an additional intermediate step here. Currently we're more restricted - we only support JSON-RPC over HTTP, not even raw JSON. While removing this restriction, we need to decide what we're doing with request IDs. Currently we're putting JSON-RPC sequence numbers into request IDs, but I don't believe we should be relying on these being usefully distinct (none of our existing clients coordinate per-sender sequence numbers over multiple connections). If we continue to include the connection ID, then we can use the order of commands per-connection to generate unique IDs, and if we really need something stronger then I expect we need to be storing a per-identity next-ID nonce.

**Comment by achamayou** [comment]
Do we need these ids exposed at the framework level?

For HTTP/1.1, there's no need to support pipelining, so we don't need this at all. For websockets, we are going to have an outer flatbuffer frame where we put the method, we can have a seqno/reqid there, identical to the current JSON-RPC mechanism.

Since the endpoints will be distinct and have distinct signatures, that seems fine?

**Comment by eddyashton** [comment]
If we can avoid exposing the IDs to the framework, I think we absolutely should! If it's only to correlate request with responses over pipelined connections, then as you say we can require some ID at the framing level but ensure this is unused in the framework logic. If we're storing requests and responses for receipt purposes (especially if this also includes read-only requests), then I think we need some additional ID for these.

**Comment by achamayou** [comment]
An additional complication is the receipt mechanism, which is valid for a (request, response, ledger entry). If the framework does not know about IDs, and we allow the app to say, send a single aggregated response for a number of requests, then framework-provided receipts stop working.

We don't need to store full requests and responses for receipt purposes, but we do need to store hash(request||noise) and hash(response||noise), for the current design (and some variant for other designs, but it's fairly unavoidable).

I don't think it follows from this that we need IDs for pure HTTP (as opposed to WS), where in the absence of pipelining, there's no ambiguity. But for WS, I don't see how we can avoid it.

**Comment by letmaik** [comment]
Why was this closed? Do HTTP endpoints now support arbitrary content types? As far as I see the response type currently cannot be binary, even in the python client.

**Comment by eddyashton** [comment]
@letmaik This has been supported for a while. The `log/private/raw_text/{id}` endpoint in the `logging.cpp` app is our main test of this - it takes `text/plain` rather than `application/javascript` in the request. For the response, the framework can return any body type (use `rpc_ctx->set_response_body(std::vector<uint8_t>)` and `rpc_ctx->set_response_header`). Most of our endpoints return either JSON on success, or plain-text on errors.

In the Python client, we only currently decode JSON or plain-text, and `raise ValueError(f"Unhandled content type: {content_type}")` for anything else. If you want to support another content-type in this client, you can add an explicit decode for it, and perhaps we should just return the unparsed body there rather than throwing.

**Comment by letmaik** [comment]
OK, the new js_generic based endpoints also don't support non-JSON responses yet. I'm mostly interested in binary responses.
