### ISSUE TITLE
Enclave::create_new_node : Unsafe memcpy with de facto sufficient bounds

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#729]
**Description**
ccf\src\enclave\enclave.h
class Enclave
create_new_node

Enclave::create_new_node() uses unbounded memcpy() for local class copies of node_cert, quote, and network_cert without checks that the target vectors are large enough.  All three of these vectors are resized subsequently in ccf\src\host\enclave.h (the assumption is that they will be reduced, otherwise it would be too late).  With a cursory code review, it appears that the de facto buffers are adequate for current inputs, but the code as-is, while perhaps not vulnerable, is brittle. 

**Expected implementation**
At the very least, protection against memory overwrites should be added.  A better solution might be to allocate properly-sized vectors at the point of copying, making the function resilient against potentially larger objects in future configurations and environments

**Comment by achamayou** [comment]
@douglasism this does happen to work now because the size provisioned is large enough (host/main.cpp:333,334,335), but you are right that the code could and should be more defensive.

Those sizes are passed through the EDL, so it's simply a matter of adding a check before the respective memcpy calls on the way out. I will fix this now, thank you for spotting it.
