### ISSUE TITLE
CCF core: error and exception handling is incomplete and inconsistent

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#777]
**Prologue**
I'm hesitant to begin with editorial comments, but since I'm an uninvited unknown guest, I feel I should. Overall, I'm impressed with the codebase. It embodies a considerable amount of complex framework and application logic. I'm not sure I could author some of the code as well as others have.  Please allow me to suggest a way to improve the code for higher resiliency.
 
**Description**
There are many cases where the code quality suffers due to a presumed lack of consensus or established best-practices regarding error and exception handling. Some classes and functions mix function error-return and exceptions in a way that results in the same confusion in their callers. 
 
A majority of the CCF's 3rdParty and std libraries use exceptions while some use function return values. But most seem to do so consistently across their interfaces. CCF code though, has an inconsistent mixed approach that often ignores the possibility of exceptions, resulting in memory leaks (#738) and unnecessary thread termination (#775).
 
For example, consider NodeState::create. It returns a complex auto type that seems brittle (I've just discovered it, so my opinion is unclear).  Along with throwing exceptions itself, it calls many functions that also do. But for some logic paths, it returns an overloaded Out structure for failure and success (if an exception has not been thrown). Among others, the function calls create_and_send_request() which always returns true --- as long as its call to send_create_request() doesn't throw an exception, which it may do directly.
 
**Recommendation**
It was not fair of me to single-out NodeState::create. There are many other examples of this problem-prone error and exception handling in the CCF codebase. Rather than creating a slew of bugs, my recommendation is that the contributors first form a consensus on the project's error and exception-handling philosophy, publish it, and then find the best way to address the most egregious examples without destabilizing the codebase.

I have several related problems that I will post issues for tomorrow, but now I must have dinner!

**Comment by achamayou** [comment]
@douglasism the CCF project is open source, and we welcome contributions in any form (https://github.com/microsoft/CCF#contributing), so you are in fact invited!

You are right to point out that error handling isn't done particularly consistently in CCF at the moment, and it's definitely something we want to improve. To give some context, there is a number of reasons for this:

1. Some code was imported from another repo (pbft), which you have perhaps noticed was written at a different time and in a different style. It is being integrated, but that's a relatively long term effort.
2. Some key dependencies (OpenEnclave, mbedtls) are written in C, and so use return codes of course.
3. The RPC format used so far (JSON-RPC) is also based on return codes.

This isn't to say that there can't be a better defined separation between the areas that handle return-code driven logic vs those that use exceptions, but that's why the current situation exists.

In addition to this, the codebase is in substantial flux, for example we are planning to remove FramedTCP and a lot of custom code associated with it now that we are using standard framing mechanisms. The multi-threading work is also affecting error handling.

So what we will do is write up error handling guidelines in the coming days, on which we would love to get your input, but having the codebase converge on these guidelines will take a little longer.

**Comment by douglasism** [comment]
@achamayou Hi Amaury, thanks for the invitation!

May I cast an early vote for exceptions rather than retvals for internal code?

**Comment by douglasism** [comment]
Or, we could go the other direction and not use C++ exceptions...

**Comment by jumaffre** [comment]
We should write guidelines on this and use `ccf_logic_error` whenever possible.

**Comment by achamayou** [comment]
Post migration away from mbedtls, we now use exceptions everywhere except where we deal with Open Enclave return codes.

We can re-open specific tickets if/when necessary, but I think this one is no longer obviously actionable.
