### ISSUE TITLE
CCF Core: Provide an interface for applications to authenticate arbitrary enclaves

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#816]
**Description**
In addition to CCF:TLS authentication, applications may want a second, deeper level of authentication. In the context of confidential computing, one natural additional level of authentication would be enclave to enclave, but not necessarily enclaves of the same services or types.

**Use Cases**
There are at least two application use cases: 

1) After users have connected to an app via CCF::TLS, the app may want to authenticate that the user is the desired enclave/service, local or remote. The authentication may be mutual.

2) Applications may be designed to use services from other enclaves. After connecting to them via CCF::TLS, the application may want to authenticate that the entity is the desired enclave, local or remote. This authentication may be mutual.

**Implementation Notes**
The current nodetonode functions are naturally CCF-centric. The CCF implementation could be generalized to support easy, (possibly mutual) enclave authentication by apps, rather than the app calling OE interfaces directly.

**Comment by douglasism** [comment]
Retracting this enhancement request. This can be accomplish via signed requests, in a stateless way.

**Comment by achamayou** [comment]
1. Native (C++) applications can do this now in their own logic. Users can send a quote for their enclave over an RPC, and the application logic can invoke OpenEnclave's verification code to satisfy itself that the client is an enclave and running specific code. I don't know what interfaces CCF could define to make this easier, I think it's fairly easy as it is. We also haven't seen use cases where clients are run in enclaves so far.

Obviously, scripting runtimes would need bindings for that, but that's broadly true for anything platform-related they want to do.

2. There is already a getQuotes RPC that clients can call to obtain the quotes for all the nodes in the current network. Once retrieved, they can be validated offline, for example with the OpenEnclave verification code (but equally well with any other piece of code that knows how to handle SGX quotes). CCF could wrap the OpenEnclave implementation, but I'm not sure what the value of doing that would be.

Signed requests do not address remote enclave attestation, all they do is provide pre-request authentication, where by default CCF relies on the identity established by the TLS session instead. CCF already supports signed requests, mostly to allow proxying (client sending requests on behalf of another client), but it clearly isn't the preferred solution in general because of the performance overhead.
