### ISSUE TITLE
kv.h::PendingTxInfo commit_reserved(): Sets committed = true, prior to commit

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#834]
(Hello CCF team, today I started looking at the Key Value store interface.)

**Description**
Of course, I might be wrong, but this set appears premature.

```
    PendingTxInfo commit_reserved()
    {
      if (committed)
        throw std::logic_error("Transaction already committed");

      committed = true; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<this is set too early, commit could fail

      if (view_list.empty())
        throw std::logic_error("Reserved transaction cannot be empty");

      auto c = commit(view_list, [this]() { return version; });
      success = c.has_value();

      if (!success)
        throw std::logic_error("Failed to commit reserved transaction");

      return {CommitSuccess::OK, {0, 0, 0}, std::move(serialise())};
    }

```

**Comment by achamayou** [comment]
Reserved transactions are special and cannot fail. They will not be part of the public interface of the store once it's defined, they are an internal implementation mechanism for KV signatures.

In a nutshell, here is why they exist and what they do. For transactions to be verifiable, they must blamable on a particular node. That means that the primary must sign the root of the merkle tree over transactions every so often, and persist that signature through consensus.

Since consensus is effectively a watermark though (ie. "up to version V"), there can't be a gap between what's signed and the signature. And so it is necessary to be able to say "we're issuing Tx v+1, which will contain a signature over the merkle tree root at v". Normal transactions would not be able to do that, because they only receive a version once they have successfully executed (at which point other transactions may have executed and changed state, invalidating the signature), so we need to be able to reserve a particular transaction version, and execute the signature once all previous transactions are complete (see ordering logic in TxStore::commit).

The only recoverable failure mode for KV transactions is conflict (reads invalidated by write sets that came in after the transaction started), but it does not apply to signature transactions because they consist of a single write to the signature table. So they cannot fail in the same way that normal transactions do.

I'll move the line you highlighted for clarity, but I hope the context helps explain why commit_reserved() is a bit special.

**Comment by douglasism** [comment]
@achamayou Thanks for the explanation Amaury.

The pattern repeats itself in `CommitSuccess commit()`. Does what you said about `commit_reserved()` apply there as well?

**Comment by achamayou** [comment]
@douglasism In commit(), committed is set at the last possible time (ie. just before serialise()). As a consequence, it must be reverted to false if an exception is thrown, which is done correctly.

This isn't the most intuitive flow, and the value of the checks in serialise() isn't immediately obvious if one thinks of it as a general public API. As an internal implementation detail though, the check does make sense and may catch invalid usage.

Efforts were made to keep the KV generic and useful as a standalone component, but as consensus guarantees have strengthened and things like forwarding and threading been added, that's become less and less realistic, and it's very unclear that the benefits outweigh the cost at this point. A good portion of the KV API only makes sense in context.
