### ISSUE TITLE
KV::commit: should recover to consistent state instead of aborting

### ISSUE THREAD

**Issue by douglasism** [microsoft/CCF#836]
**Description**
It was good to see the fixes for #782. I wished I would have seen the discussion about abort in `frontend.h`. I would have advocated for an exception instead of aborting, and if it were critical that the enclave abort, that is, that the exception not be swallowed when the stack is unwound, then a critical exception could have been defined, or even by ccf convention, std::runtime_error or whatever. This way the enclave unwinds, dtors get called, etc. `oe_abort` could then be called from main or similar.

More broadly, I find it interesting that the single place in all of CCF where an abort is critical, is when KV serialization fails. If this failure were representative of the class of "must abort!", CCF would have many abort instances. (More discussion of this is in #577 and #338.)

**Minimum Recommendation**
Anyway, if the code must abort, then it would be better to call `oe_abort` for possible TEE-specific handling.

**Comment by achamayou** [comment]
@douglasism I did go for an exception at first, but there are a couple of levels above that catch (legitimately), and this error is really not recoverable.

I'm not sure what good calling the destructors would be in this case, if a Tx is committed but not serialised, it's really best to stop node operations right away. From a security standpoint, a host can interrupt an enclave any time, without giving any dtors the opportunity to execute, so there's no benefit from that perspective either. Do you have a specific benefit in mind?

It's worth noting that abort() _is_ oe_abort() in the enclave, provided by oecorelibc. There is no way to raise signals directly from enclave code of course.

I don't understand your point about #577 and #388, which are about the exact same issue: what to do if a transaction does not serialise successfully. I don't think there are that many such errors, but if you spot others please do raise them.

To give some context, this serialisation error is particularly problematic because it occurs after a change has been applied to the KV in a locally committed state, but before it can be replicated to global consensus. In normal flow, transactions always succeed, if after a few retries in case of conflict, but in this case there is no way to succeed since the transaction cannot replicate. While this is happening, more transactions are locally committed on top of a state that can never replicate.

A better (but more complex) handling of this situation would be to roll back, and trigger an election (which happens anyway when the node aborts) while keeping the node alive. That's an optimisation but it doesn't change any of the guarantees (not even liveness), and it will not work for the most common serialisation issue which is running out of memory. We might get to it in the future, but there are a lot of items with a better cost/benefit ratio on our list first.

**Comment by douglasism** [comment]
@achamayou Hi Amaury, stack unwinding is important for dtor execution, and dtor execution is important for secure high-value secret handling, which in turn, is important for secure CocoNodes. (Please see my new comment: https://github.com/microsoft/CCF/issues/793#issuecomment-585966754.)

Thanks for pointing out that `abort()` is `oe_abort()` in an enclave. Another refinement is that unhandled C++ exceptions call `terminate`, not `abort`.

I apologize for making a broad unfounded claim that there are many “abort” instances in the code (if KV::serialization were the representative example). It was an intuitive claim based on my review. But when I made a quick effort to find a similar example, I failed. (I will work on this more! though.)

Regarding #388 and #577: kv::serialization is becoming my poster-code for low framework resiliency. I would expect, given the project’s goal of high availability, that unhandled exceptions (or terminates/aborts) would be rare and cause for immediate remediation. I liked both @jumaffre’s and @eddyashton’s spirit and ideas for recovery, but was surprised that the team accepted abort as a solution. This decision leaves in place a potential DoS against a node. And even in the case of non-malicious traffic, it would seem that if it were known that serialization had Tx size limitations, that the framework would detect and block the Tx prior to commit.  (If there is a possible disparity between what `commit()` and `serialize()` can support due to memory constraints, would it be possible to try `serialize.prep()` on a projection of Tx first, then `commit(), serialize.final()`?)

=*preachy*=  More broadly: I understand the pressure of project trade-offs when weighing feature costs and benefits, but enclave resilience, especially to input, is not a feature.  It’s a fundamental quality of high-availability services. (Perhaps the only reason for self-termination would be evidence of enclave attack. Low memory conditions should be handled via service throttling.) CCF should have a core set of fundamental properties that must always be true and all other work should stop when they fail. =*preachy*=

**Comment by achamayou** [comment]
@douglasism `terminate` defaults to calling `abort`, unless a custom terminate handler is set. We do not set custom handlers, and we want to shut down as quickly as possible because leaving the node up means extending a chain of local commits that will can never converge, leading to poor usability.

Pre-computing serialised Tx is a non-trivial change, because some of the elements of the transaction (such as the version) are only known once it is committed. It would also be extremely inefficient with the current serialisation interface because it would inevitably lead to double serialisation. We are planning to change serialisation formats in the near future, and that will make this particular change easier, but at the moment I'm afraid it's not something we are planning to look at with high priority.

It should be noted that a certain amount of defensiveness is expected from application writers, particularly from those who use C++. It is of course not possible for the framework to offer hard guarantees about liveness while executing arbitrary native user-specified code.

It's also worth noting that single node DoS is not that critical an event, our threat model is that a number of hosts are under control of the attacker, and it is trivial for a host to cut off all traffic to an enclave, leading to a single node DoS. The properties we guarantee are integrity and confidentiality, availability is qualified.

I hope this helps explain why it isn't a priority for us to invest in handling this particular situation better at the moment. You are of course free to disagree, and to propose pull requests implementing the behaviour you would prefer, which we would be very happy to review.

**Comment by eddyashton** [comment]
@douglasism Since app writers can define their own serialization functions for their own types, we can't predict a relationship between `sizeof(Tx)` and `sizeof(serialized(Tx))`. We expect app writers to use various kinds of DoS safeguards (don't let transactions create infinite loops, don't allow transactions that use too much memory during execution or serialization) but we can't block these in general in the framework. We're hoping to move to flatbuffer serialization in future, potentially with a formally verified serializer. This removes the arbitrary-user-serializers threat, and should ensure the size of a transaction and its serialization are _similar_, but still doesn't remove the risk of errors which could be thrown from serialization.

We currently require `commit()` to happen before `serialise()` because we need the commit version to encrypt, and we encrypt during serialisation. We could relax this at the cost of extra memory useage, but we could still have exceptions (including out-of-memory) during encryption that are just as fatal.

**Comment by douglasism** [comment]
@achamayou @eddyashton  Thanks for taking the time to respond in detail.  

The problem with `kv::commit()` is larger than the inability to deal with an oversized `serialise()`.  KV transactions should be atomic, either succeeding fully and arriving in a new consistent state or failing and returning to the previous consistent state. But atomicity fails with `kv::commit()` . The first subcall to `commit(view_list..)` cannot be rolled back(with the current design/impl), and subsequent failure in `kv::commit()` leaves the node in an inconsistent state, thus the idea to abort.  But that option is a very poor one -- especially for a framework designed to support “…highly available applications”.  

Pushing the responsibility to the app won’t work. There’s a lot of code left to run after the first subcall to `commit(view_list..)`. Along with `serialise()`, the second subcall to another `commit(version` is non-trivial --- both of these functions could throw exceptions for reasons other than oversized input. How is an app going to code for that? It will be just as impossible for the app to recover as it is now for CCF. Further, it’s likely that the client will retry the transaction against another node. Pop, pop, pop across the service.

The soundness of KV is central to CCF. A core quality of CCF should be its resilience. Problems like these shouldn’t be brushed aside with an abort. CCF’s poor error/exception handling, and the related inability to recover and remain in a consistent state, will be blockers for broad adoption. The investment the project makes in solid code will pay off significantly. Consider the debugging time you’ll save for your app devs and yourselves! #777 is still without a milestone. I’m confident that you can find a way to get back to a consistent service state in `kv::commit()`.  I have many ideas for #777 that I’m willing to share, but you must make me feel a little more like a pig than a chicken (at the Ham & Eggs Restaurant). 

I’ve made my points and I will not belabor them further. You have a different, more informed view of the project. Please don’t feel compelled to respond to my rantings. I won't be offended with just a "Thanks for the input!"

**Comment by achamayou** [comment]
To address your first point, transactions are absolutely atomic from a user point of view, regardless of whether serialisation fails or not. Serialisation failures prevent them from going to the ledger and to other nodes, but they do not cause the node to reach a locally inconsistent state. They prevent the _network_ from making progress, but that's a different issue, not to be confused with transaction atomicity or local inconsistency.
What is undesirable in this situation is that locally committed state has effectively forked away, and global state can never converge on it, because it cannot be replicated. There is no alternative to rolling back at this point. This can be done of two ways:

1. The node shuts down, as it does now. A new leader is elected. The operator has to provision a new node to maintain capacity.
2. The node rolls back, and goes back to a previous known good state and resumes from there. This may or may not be possible, if serialisation fails because the node ran out of memory, this is very unlikely to succeed!

Option 2 is substantially more complex to implement, and I disagree with your absolute statements about it being worse for availability. Having the primary roll back and resume isn't obviously faster than an election, and will quite possibly result in nothing more than a delayed election.
It also does not absolve the operator from carefully monitoring the number of nodes and provisioning new ones when they fail (remember, the host is under control of the attacker, it can cut off enclaves from the network at will).

I also don't want to belabor this point too much either, and spend more time discussing it than it would to implement Option 2! But this hopefully explains why we have not prioritised this work even though we've discussed it a while back, we have other tasks we believe are more important at the moment.

I am not entirely sure what you mean by feeling more like a pig than a chicken, perhaps I am missing some cultural context. I would however like to re-state that you are very welcome to contribute more than issues and to propose PRs implementing the changes you wish to see.

**Comment by douglasism** [comment]
@achamayou Thanks for the additional details. I disagree with some points, but we move on.

https://en.wikipedia.org/wiki/The_Chicken_and_the_Pig
