### ISSUE TITLE
Enable error logging during initial create_node ECALL

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#857]
We currently make 2 ECALLs: `enclave_create_node` and `enclave_run`. This makes the code in `enclave_create_node` special, it runs before the host is pumping the outbound ringbuffer so its log messages are ignored on failure.

We should combine these, with a single `enclave_run` ECALL which does creation as its first step. The outputs from the current `create` (node cert etc) can be written over the ringbuffer. This way any errors during processing of the `Create` RPC will be easier to track, as they will fail through similar paths to a standard RPC.

**Comment by achamayou** [comment]
@eddyashton having had a quick look now, I think the merge may be more trouble than it's worth, because what the split allows is a single-threaded setup phase for the node, before spawning all the threads that enclave_run().

A single merged create_node_and_run() would need to race for a setup lock, block while the winner sets up etc.

I think we could realise much if not all the benefit of the merge just by consuming log messages from the ringbuffer in the event of a failed create_node()?

**Comment by eddyashton** [comment]
@achamayou Since the 'first' thread that calls `enclave_run` already takes a very different path, I think it would still be helpful to collapse that into a single ECALL? When the node is sufficiently 'created' that the host wants to create additional worker threads, those worker threads can either reuse the same ECALL and skip all of the creation, or use a still-separate ECALL. The latter seems nice, to more clearly distinguish the main thread from the workers, outside of "which managed to mark themselves as a worker first". That probably still requires a blocking loop somewhere, where the main enclave thread waits for the workers to initialise themselves before it proceeds to anything that assumes `ThreadMessaging` is initialised, but that doesn't sound too onerous?

The main goal is definitely consuming log messages/common error reporting. But I think any other approach to that would also be complex - to pump the ringbuffer when `create_node` fails, we need to re-do a chunk of the setup that we would do in the successful case, for a while, and then exit?

**Comment by achamayou** [comment]
I don't think I understand the simplification we would get from this merge. Once the RB is setup, we can and do log, so the dispatcher/workers distinction doesn't seem super useful?

We do have some initial setup though, which is more easily done single threaded in `create_node`, if we just make sure we set up the RB early, and set a failure RC otherwise, we can on failure go pump messages out rather than continue with the setup?
