### ISSUE TITLE
Enable governance history test with PBFT

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#953]
governance maps are derived with pbft enabled and so they don't get written to the ledger

`governance_history` test should be enabled when this issue is resolved

**Comment by jumaffre** [comment]
Looking at the `governance_history` test in more detail, it seems to me that the only thing we need to do is write a parser for the PBFT ledger that we can use from our e2e infra. Since requests get written to the ledger, we can then directly read the signed governance requests from there. Ideally the ledger format for Raft and PBFT should be unified.

**Comment by ashamis** [comment]
moving to AFT
